export const idCardDetails = {
    slNo: "024",
    idCardPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?fit=crop&w=800&q=80",
    name: "Aditi Rao",
    firstName: "Aditi",
    middleName: "-",
    lastName: "Rao",
    fatherSName: "Venkatesh Rao",
    fatherFirstName: "Venkatesh",
    fatherMiddleName: "-",
    fatherLastName: "Rao",
    dateOfBirth: "11-Nov-2000",
    gender: "Female",
    designation: "SOC Analyst Trainee",
    department: "Security Operations Center (SOC)",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Technical Trainee ID",
    employeeStudentMemberId: "CRCCF-TRN-024",
    idCardNumber: "IDC-2024-TRN24",
    issueDate: "15-Jan-2024",
    validFrom: "15-Jan-2024",
    expiryDate: "14-Jan-2025",
    mobileNumber: "+91 9849112233",
    emailId: "aditi.rao@trainee.crccf.org",
    address: "HITEC City, Hyderabad, Telangana, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "SOC floor trainee clearance and incident drill participant"
};
