export const certificateDetails = {
    slNo: "027",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Insp. Rakesh Solanki",
    certificateHolderFirstName: "Rakesh",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Solanki",
    fatherSName: "Vikram Solanki",
    fatherFirstName: "Vikram",
    fatherMiddleName: "-",
    fatherLastName: "Solanki",
    dateOfBirth: "07-Aug-1989",
    gender: "Male",
    certificateName: "Cyber Crime Investigation Certificate",
    certificateType: "Law Enforcement Specialized Credential",
    courseQualificationName: "Advanced Open Source Intelligence (OSINT) & Digital Evidence Extraction",
    institutionName: "Cyber Crime Investigation Training Academy",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-CIC-2024-027",
    certificateNumber: "CERT-CIC-8927",
    issueDate: "16-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Distinction with Honors",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director of Investigative Training, CRCCF",
    mobileNumber: "+91 9876543127",
    emailId: "rakesh.solanki@example.com",
    address: "Police Officers Colony, Bhopal, Madhya Pradesh, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
