export const idCardDetails = {
    slNo: "026",
    idCardPhoto: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?fit=crop&w=800&q=80",
    name: "Priyanka Saxena",
    firstName: "Priyanka",
    middleName: "-",
    lastName: "Saxena",
    fatherSName: "Anil Saxena",
    fatherFirstName: "Anil",
    fatherMiddleName: "-",
    fatherLastName: "Saxena",
    dateOfBirth: "14-Mar-1995",
    gender: "Female",
    designation: "Research Associate - AI Security",
    department: "AI & Autonomous Defense Research Cell",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Research Associate ID",
    employeeStudentMemberId: "CRCCF-RSA-026",
    idCardNumber: "IDC-2024-RSA26",
    issueDate: "01-Jul-2023",
    validFrom: "01-Jul-2023",
    expiryDate: "30-Jun-2026",
    mobileNumber: "+91 9811776655",
    emailId: "priyanka.s@crccf.org",
    address: "Sector 18, Noida, Uttar Pradesh, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Full access to high-performance AI compute cluster"
};
