export const idCardDetails = {
    slNo: "010",
    idCardPhoto: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?fit=crop&w=800&q=80",
    name: "Suresh Patra",
    firstName: "Suresh",
    middleName: "-",
    lastName: "Patra",
    fatherSName: "Bichitra Patra",
    fatherFirstName: "Bichitra",
    fatherMiddleName: "-",
    fatherLastName: "Patra",
    dateOfBirth: "20-Jan-1993",
    gender: "Male",
    designation: "Temporary Technical Support Staff",
    department: "Logistics & IT Helpdesk",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Temporary Staff ID",
    employeeStudentMemberId: "CRCCF-TMP-010",
    idCardNumber: "IDC-2024-TMP10",
    issueDate: "01-Feb-2024",
    validFrom: "01-Feb-2024",
    expiryDate: "31-Jul-2024",
    mobileNumber: "+91 9861009988",
    emailId: "suresh.p@crccf.org",
    address: "Lane 5, Saheed Nagar, Bhubaneswar, Odisha, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Temporary hardware access and dispatch duties"
};
