export const certificateDetails = {
    slNo: "001",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Ananya Roy",
    certificateHolderFirstName: "Ananya",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Roy",
    fatherSName: "Subhas Roy",
    fatherFirstName: "Subhas",
    fatherMiddleName: "-",
    fatherLastName: "Roy",
    dateOfBirth: "12-Jul-2001",
    gender: "Female",
    certificateName: "Internship Certificate",
    certificateType: "Practical Cybersecurity Internship",
    courseQualificationName: "Cyber Forensics & Incident Response Internship",
    institutionName: "CRCCF Cyber Intelligence Center",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-IC-2024-001",
    certificateNumber: "CERT-IC-8901",
    issueDate: "15-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Outstanding)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director of Training, CRCCF",
    mobileNumber: "+91 9876543101",
    emailId: "ananya.roy@example.com",
    address: "Sector 5, Salt Lake, Kolkata, West Bengal, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
