export const certificateDetails = {
    slNo: "034",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Pallavi Saxena",
    certificateHolderFirstName: "Pallavi",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Saxena",
    fatherSName: "Deepak Saxena",
    fatherFirstName: "Deepak",
    fatherMiddleName: "-",
    fatherLastName: "Saxena",
    dateOfBirth: "14-Dec-1996",
    gender: "Female",
    certificateName: "Cyber Threat Intelligence Certificate",
    certificateType: "CTI Professional Certification",
    courseQualificationName: "Adversary TTPs, MITRE ATT&CK & Dark Web Threat Intelligence",
    institutionName: "CRCCF Threat Intelligence Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-CTI-2024-034",
    certificateNumber: "CERT-CTI-8934",
    issueDate: "19-Aug-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director of Intelligence, CRCCF",
    mobileNumber: "+91 9876543134",
    emailId: "pallavi.saxena@example.com",
    address: "Vaishali Nagar, Jaipur, Rajasthan, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
