export const idCardDetails = {
    slNo: "021",
    idCardPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?fit=crop&w=800&q=80",
    name: "Rahul Singhania",
    firstName: "Rahul",
    middleName: "-",
    lastName: "Singhania",
    fatherSName: "O. P. Singhania",
    fatherFirstName: "O.",
    fatherMiddleName: "P.",
    fatherLastName: "Singhania",
    dateOfBirth: "21-Sep-1996",
    gender: "Male",
    designation: "Certified Academy Graduate",
    department: "CRCCF Training Academy Alumni",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Alumni ID",
    employeeStudentMemberId: "CRCCF-ALM-021",
    idCardNumber: "IDC-2024-ALM21",
    issueDate: "15-Jul-2023",
    validFrom: "15-Jul-2023",
    expiryDate: "Lifetime",
    mobileNumber: "+91 9833445566",
    emailId: "rahul.s@alumni.crccf.org",
    address: "Salt Lake Sector 5, Kolkata, West Bengal, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Certified graduate of Cyber Warfare Masters Fellowship"
};
