export const certificateDetails = {
    slNo: "001",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Subrajit Sharma",
    certificateHolderFirstName: "Subrajit",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Sharma",
    fatherSName: "Sanjay Kumar",
    fatherFirstName: "Sanjay",
    fatherMiddleName: "-",
    fatherLastName: "Kumar",
    dateOfBirth: "15-Aug-1995",
    gender: "Male",
    certificateName: "Certified Cyber Crime & Forensic Specialist (CCFS)",
    certificateType: "Professional Certification",
    courseQualificationName: "Advanced Cyber Defense & Incident Response",
    institutionName: "National Cyber Security Training Institute",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRT-2023-009",
    certificateNumber: "CCFS-992140",
    issueDate: "15-Oct-2023",
    passingYear: "2023",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director of Certification, CRCCF",
    mobileNumber: "+91 9876543210",
    emailId: "subrajit@example.com",
    address: "123, Tech Park Avenue, Block C, Bhubaneswar, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate",
};