export const certificateDetails = {
    slNo: "Sample Sl No",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Sample Certificate Holder Name",
    fatherSName: "Sample Father's Name",
    dateOfBirth: "Sample Date of Birth",
    gender: "Sample Gender",
    certificateName: "Sample Certificate Name",
    certificateType: "Sample Certificate Type",
    courseQualificationName: "Sample Course / Qualification Name",
    institutionName: "Sample Institution Name",
    boardUniversity: "Sample Board / University",
    registrationNumber: "Sample Registration Number",
    certificateNumber: "Sample Certificate Number",
    issueDate: "Sample Issue Date",
    passingYear: "Sample Passing Year",
    gradeMarks: "Sample Grade / Marks",
    certificateValidity: "Sample Certificate Validity",
    issuingAuthority: "Sample Issuing Authority",
    mobileNumber: "Sample Mobile Number",
    emailId: "Sample Email ID",
    address: "Sample Address",
    certificateStatus: "Sample Certificate Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};