export const digitalSignatureDetails = {
    slNo: "Sample Sl No",
    signaturePreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    signatoryName: "Sample Signatory Name",
    fatherSName: "Sample Father's Name",
    dateOfBirth: "Sample Date of Birth",
    gender: "Sample Gender",
    designation: "Sample Designation",
    department: "Sample Department",
    organization: "Sample Organization",
    digitalSignatureId: "Sample Digital Signature ID",
    certificateSerialNumber: "Sample Certificate Serial Number",
    certificateType: "Sample Certificate Type",
    certificateIssuingAuthority: "Sample Certificate Issuing Authority",
    certificateIssuedDate: "Sample Certificate Issued Date",
    certificateValidFrom: "Sample Certificate Valid From",
    certificateExpiryDate: "Sample Certificate Expiry Date",
    signatureAlgorithm: "Sample Signature Algorithm",
    signaturePurpose: "Sample Signature Purpose",
    registeredEmailId: "Sample Registered Email ID",
    mobileNumber: "Sample Mobile Number",
    address: "Sample Address",
    signatureStatus: "Sample Signature Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};