export const digitalSignatureDetails = {
    slNo: "001",
    signaturePreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    signatoryName: "Subrajit Sharma",
    signatoryFirstName: "Subrajit",
    signatoryMiddleName: "-",
    signatoryLastName: "Sharma",
    signatureId: "DS-2023-9912",
    signatureRegistrationId: "DS-REG-009",
    fatherSName: "Sanjay Kumar",
    fatherFirstName: "Sanjay",
    fatherMiddleName: "-",
    fatherLastName: "Kumar",
    dateOfBirth: "15-Aug-1995",
    gender: "Male",
    designation: "Chief Information Security Officer",
    department: "Executive Cryptographic Operations",
    organization: "CR Cyber Crime Foundation",
    digitalSignatureId: "DS-CERT-882194",
    certificateSerialNumber: "7A4F-99B2-E108-CC31",
    certificateType: "Class 3 SHA-256 Digital Signature Certificate",
    certificateIssuingAuthority: "National Certifying Authority of India (CCA)",
    certificateIssuedDate: "01-Sep-2023",
    certificateValidFrom: "01-Sep-2023",
    certificateExpiryDate: "31-Aug-2026",
    signatureAlgorithm: "RSA 2048-bit with SHA-256",
    signaturePurpose: "Official Document Signing & Forensic Verification",
    registeredEmailId: "subrajit@example.com",
    mobileNumber: "+91 9876543210",
    address: "123, Tech Park Avenue, Block C, Bhubaneswar, India",
    signatureStatus: "Valid & Cryptographically Verified",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Public Key Infrastructure (PKI) Audit Division",
};