export const agreementDetails = {
    firstPartyName: "Subrajit Sharma",
    firstPartyFirstName: "Subrajit",
    firstPartyMiddleName: "-",
    firstPartyLastName: "Sharma",
    secondPartyName: "TechCorp Global Inc.",
    agreementTitle: "Software Development NDA",
    agreementPurpose: "Confidentiality for Project Alpha",
    agreementType: "Non-Disclosure Agreement (NDA)",
    agreementActivity: "Data Protection & IP Rights",
    registrationNumber: "009",
    status: "Active",
    validity: "5 Years",
    expireDate: "15-Oct-2028",
    authorizeSignaturePersonName: "Ramesh Sharma",
    authorizeSignatoryFirstName: "Ramesh",
    authorizeSignatoryMiddleName: "-",
    authorizeSignatoryLastName: "Sharma",
    typeOfSign: "Digital Signature (e-Sign)"
};
