export const certificateDetails = {
    slNo: "023",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Dr. Nandita Bhattacharya",
    certificateHolderFirstName: "Nandita",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Bhattacharya",
    fatherSName: "Dr. Debasis Bhattacharya",
    fatherFirstName: "Debasis",
    fatherMiddleName: "-",
    fatherLastName: "Bhattacharya",
    dateOfBirth: "12-Sep-1984",
    gender: "Female",
    certificateName: "Research Contribution Certificate",
    certificateType: "Scientific Research Recognition",
    courseQualificationName: "Post-Quantum Cryptography & Resilient Threat Modeling",
    institutionName: "CRCCF Cyber Research & Innovation Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-RCC-2024-023",
    certificateNumber: "CERT-RCC-8923",
    issueDate: "18-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Principal Investigator Citation",
    certificateValidity: "Permanent Record",
    issuingAuthority: "Director of Research, CRCCF",
    mobileNumber: "+91 9876543123",
    emailId: "dr.nandita@example.com",
    address: "Ballygunge Circular Road, Kolkata, West Bengal, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
