export const certificateDetails = {
    slNo: "017",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Priya Swaminathan",
    certificateHolderFirstName: "Priya",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Swaminathan",
    fatherSName: "R. Swaminathan",
    fatherFirstName: "R.",
    fatherMiddleName: "-",
    fatherLastName: "Swaminathan",
    dateOfBirth: "27-Jun-1996",
    gender: "Female",
    certificateName: "Recognition Certificate",
    certificateType: "Institutional Recognition",
    courseQualificationName: "Critical Incident Response & Evidence Preservation Under Pressure",
    institutionName: "CRCCF Cyber Incident Response Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-RC-2024-017",
    certificateNumber: "CERT-RC-8917",
    issueDate: "04-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Distinguished Service",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director General, CRCCF",
    mobileNumber: "+91 9876543117",
    emailId: "priya.swami@example.com",
    address: "Mylapore, Chennai, Tamil Nadu, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
