export const idCardDetails = {
    slNo: "039",
    idCardPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    name: "Sanjay Rathore",
    firstName: "Sanjay",
    middleName: "-",
    lastName: "Rathore",
    fatherSName: "Virendra Rathore",
    fatherFirstName: "Virendra",
    fatherMiddleName: "-",
    fatherLastName: "Rathore",
    dateOfBirth: "05-Aug-1991",
    gender: "Male",
    designation: "Registered Campus Visitor",
    department: "Visitor Protocol & Reception Bureau",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Visitor ID",
    employeeStudentMemberId: "CRCCF-VIS-039",
    idCardNumber: "IDC-2024-VIS39",
    issueDate: "15-Sep-2026",
    validFrom: "15-Sep-2026",
    expiryDate: "15-Sep-2026",
    mobileNumber: "+91 9876001122",
    emailId: "sanjay.r@visitor.crccf.org",
    address: "Indore, Madhya Pradesh, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Single-day authorized visitor pass for Conference Room 4"
};
