export const idCardDetails = {
    slNo: "038",
    idCardPhoto: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?fit=crop&w=800&q=80",
    name: "Barkha Mukherjee",
    firstName: "Barkha",
    middleName: "-",
    lastName: "Mukherjee",
    fatherSName: "S. K. Mukherjee",
    fatherFirstName: "S.",
    fatherMiddleName: "K.",
    fatherLastName: "Mukherjee",
    dateOfBirth: "11-Nov-1988",
    gender: "Female",
    designation: "Accredited Senior Journalist",
    department: "Cyber Crime Press & Media Bureau",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Press & Media ID",
    employeeStudentMemberId: "CRCCF-MED-038",
    idCardNumber: "IDC-2024-MED38",
    issueDate: "01-Jan-2023",
    validFrom: "01-Jan-2023",
    expiryDate: "31-Dec-2025",
    mobileNumber: "+91 9810998877",
    emailId: "barkha.m@press.crccf.org",
    address: "Press Enclave, Saket, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Accredited media badge for press briefings and public disclosures"
};
