export const idCardDetails = {
    slNo: "016",
    idCardPhoto: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?fit=crop&w=800&q=80",
    name: "Amit Bhargava",
    firstName: "Amit",
    middleName: "-",
    lastName: "Bhargava",
    fatherSName: "P. L. Bhargava",
    fatherFirstName: "P.",
    fatherMiddleName: "L.",
    fatherLastName: "Bhargava",
    dateOfBirth: "23-Feb-1981",
    gender: "Male",
    designation: "Institutional Alliance Partner",
    department: "Corporate Partnerships & MoUs",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Partner Organization ID",
    employeeStudentMemberId: "CRCCF-PTR-016",
    idCardNumber: "IDC-2024-PTR16",
    issueDate: "01-Jul-2023",
    validFrom: "01-Jul-2023",
    expiryDate: "30-Jun-2026",
    mobileNumber: "+91 9820556677",
    emailId: "amit.bhargava@partner-crccf.org",
    address: "World Trade Centre, Cuffe Parade, Mumbai, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized joint industry partner for cyber defense initiatives"
};
