export const certificateDetails = {
    slNo: "011",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Divya Menon",
    certificateHolderFirstName: "Divya",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Menon",
    fatherSName: "Suresh Menon",
    fatherFirstName: "Suresh",
    fatherMiddleName: "-",
    fatherLastName: "Menon",
    dateOfBirth: "16-Jul-2000",
    gender: "Female",
    certificateName: "Webinar Certificate",
    certificateType: "Virtual Masterclass Webinar",
    courseQualificationName: "Modern Web Application Security & API Defense",
    institutionName: "CRCCF Global Virtual Learning",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-WC-2024-011",
    certificateNumber: "CERT-WC-8911",
    issueDate: "28-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Certified Completion",
    certificateValidity: "Permanent Record",
    issuingAuthority: "Webinar Program Director, CRCCF",
    mobileNumber: "+91 9876543111",
    emailId: "divya.menon@example.com",
    address: "Kakkanad, Kochi, Kerala, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
