export const certificateDetails = {
    slNo: "021",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Subrajit Sharma",
    certificateHolderFirstName: "Subrajit",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Sharma",
    fatherSName: "Sanjay Kumar",
    fatherFirstName: "Sanjay",
    fatherMiddleName: "-",
    fatherLastName: "Kumar",
    dateOfBirth: "15-Aug-1995",
    gender: "Male",
    certificateName: "Employee of the Month Certificate",
    certificateType: "Internal Staff Recognition",
    courseQualificationName: "Employee of the Month for Diligence & Threat Triage Mastery",
    institutionName: "CRCCF Directorate of Operations",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-EOM-2024-021",
    certificateNumber: "CERT-EOM-8921",
    issueDate: "01-Sep-2024",
    passingYear: "2024",
    gradeMarks: "Star Performer",
    certificateValidity: "Lifetime",
    issuingAuthority: "Head of Operations, CRCCF",
    mobileNumber: "+91 9876543210",
    emailId: "subrajit@example.com",
    address: "123 Tech Park Avenue, Bhubaneswar, Odisha, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
