export const idCardDetails = {
    slNo: "033",
    idCardPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?fit=crop&w=800&q=80",
    name: "Swati Tripathy",
    firstName: "Swati",
    middleName: "-",
    lastName: "Tripathy",
    fatherSName: "R. C. Tripathy",
    fatherFirstName: "R.",
    fatherMiddleName: "C.",
    fatherLastName: "Tripathy",
    dateOfBirth: "12-Sep-1994",
    gender: "Female",
    designation: "Project Associate - Cyber Forensics",
    department: "Cyber Lab Implementation Project",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Project Associate ID",
    employeeStudentMemberId: "CRCCF-PRA-033",
    idCardNumber: "IDC-2024-PRA33",
    issueDate: "01-Aug-2023",
    validFrom: "01-Aug-2023",
    expiryDate: "31-Jul-2026",
    mobileNumber: "+91 9861445566",
    emailId: "swati.t@crccf.org",
    address: "Infocity Road, Patia, Bhubaneswar, Odisha, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized for lab infrastructure deployment across state police stations"
};
