export const certificateDetails = {
    slNo: "003",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Sneha Mukherjee",
    certificateHolderFirstName: "Sneha",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Mukherjee",
    fatherSName: "Ashish Mukherjee",
    fatherFirstName: "Ashish",
    fatherMiddleName: "-",
    fatherLastName: "Mukherjee",
    dateOfBirth: "22-Nov-1999",
    gender: "Female",
    certificateName: "Course Certificate",
    certificateType: "Certificate Course",
    courseQualificationName: "Certified Cyber Threat Analyst (CCTA)",
    institutionName: "National Cyber Security Institute",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-CC-2024-003",
    certificateNumber: "CERT-CC-8903",
    issueDate: "05-Aug-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Dean of Cyber Studies, CRCCF",
    mobileNumber: "+91 9876543103",
    emailId: "sneha.m@example.com",
    address: "Park Street, Kolkata, West Bengal, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
