export const idCardDetails = {
    slNo: "017",
    idCardPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?fit=crop&w=800&q=80",
    name: "Pooja Hegde",
    firstName: "Pooja",
    middleName: "-",
    lastName: "Hegde",
    fatherSName: "B. M. Hegde",
    fatherFirstName: "B.",
    fatherMiddleName: "M.",
    fatherLastName: "Hegde",
    dateOfBirth: "17-Jul-1994",
    gender: "Female",
    designation: "Certified Cybersecurity Member",
    department: "Professional Membership Cell",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Membership ID",
    employeeStudentMemberId: "CRCCF-MBR-017",
    idCardNumber: "IDC-2024-MBR17",
    issueDate: "01-Jan-2024",
    validFrom: "01-Jan-2024",
    expiryDate: "31-Dec-2025",
    mobileNumber: "+91 9845778899",
    emailId: "pooja.hegde@members.crccf.org",
    address: "Indiranagar 100ft Road, Bengaluru, Karnataka, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Active professional member of CRCCF Global Forum"
};
