export const idCardDetails = {
    slNo: "036",
    idCardPhoto: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?fit=crop&w=800&q=80",
    name: "Farhan Ali",
    firstName: "Farhan",
    middleName: "-",
    lastName: "Ali",
    fatherSName: "Tariq Ali",
    fatherFirstName: "Tariq",
    fatherMiddleName: "-",
    fatherLastName: "Ali",
    dateOfBirth: "20-Apr-1991",
    gender: "Male",
    designation: "Community Liaison Officer",
    department: "Public Grievance & Citizen Assistance Cell",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Community Representative ID",
    employeeStudentMemberId: "CRCCF-COM-036",
    idCardNumber: "IDC-2024-COM36",
    issueDate: "15-May-2023",
    validFrom: "15-May-2023",
    expiryDate: "14-May-2026",
    mobileNumber: "+91 9822778899",
    emailId: "farhan.ali@crccf.org",
    address: "Camp Area, MG Road, Pune, Maharashtra, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized citizen counselor for localized cyber fraud reporting"
};
