export const mentorshipPrograms = [
    { id: "ethical-security-workshop", title: "Ethical Security Workshop" },
    { id: "cybersecurity-essentials-workshop", title: "Cybersecurity Essentials Workshop" },
    { id: "network-security-workshop", title: "Network Security Workshop" },
    { id: "soc-analyst-workshop", title: "SOC Analyst Workshop (Security Operations Center)" },
    { id: "malware-analysis-workshop", title: "Malware Analysis Workshop" },
    { id: "react-js-workshop", title: "React JS Workshop" },
    { id: "full-stack-development-workshop", title: "Full Stack Development Workshop" },
    { id: "mobile-app-development-workshop", title: "Mobile App Development Workshop" },
    { id: "api-development-workshop", title: "API Development Workshop" },
    { id: "git-github-workshop", title: "Git & GitHub Workshop" },
    { id: "data-analytics-workshop", title: "Data Analytics Workshop" },
    { id: "data-science-workshop", title: "Data Science Workshop" },
    { id: "machine-learning-workshop", title: "Machine Learning Workshop" },
    { id: "generative-ai-workshop", title: "Generative AI Workshop" },
    { id: "prompt-engineering-workshop", title: "Prompt Engineering Workshop" },
    { id: "uiux-design-workshop", title: "UI/UX Design Workshop" },
    { id: "figma-masterclass-workshop", title: "Figma Masterclass Workshop" },
    { id: "graphic-design-workshop", title: "Graphic Design Workshop" },
    { id: "digital-marketing-workshop", title: "Digital Marketing Workshop" },
    { id: "seo-workshop", title: "SEO Workshop" },
    { id: "social-media-marketing-workshop", title: "Social Media Marketing Workshop" },
    { id: "content-marketing-workshop", title: "Content Marketing Workshop" },
    { id: "product-management-workshop", title: "Product Management Workshop" },
    { id: "business-development-workshop", title: "Business Development Workshop" },
    { id: "entrepreneurship-workshop", title: "Entrepreneurship Workshop" },
    { id: "cyber-law-workshop", title: "Cyber Law Workshop" },
    { id: "digital-rights-workshop", title: "Digital Rights Workshop" },
    { id: "legal-research-workshop", title: "Legal Research Workshop" },
    { id: "cloud-computing-workshop", title: "Cloud Computing Workshop" },
    { id: "devops-fundamentals-workshop", title: "DevOps Fundamentals Workshop" },
    { id: "docker-kubernetes-workshop", title: "Docker & Kubernetes Workshop" },
    { id: "blockchain-development-workshop", title: "Blockchain Development Workshop" },
    { id: "internet-of-things-workshop", title: "Internet of Things (IoT) Workshop" },
    { id: "database-management-workshop", title: "Database Management Workshop" },
    { id: "software-testing-automation-workshop", title: "Software Testing Automation Workshop" },
    { id: "reverse-engineering-workshop", title: "Reverse Engineering Workshop" },
    { id: "threat-intelligence-workshop", title: "Threat Intelligence Workshop" },
    { id: "cyber-forensics-workshop", title: "Cyber Forensics Workshop" },
    { id: "osint-investigation-workshop", title: "OSINT Investigation Workshop (Open Source Intelligence)" },
    { id: "incident-response-workshop", title: "Incident Response Workshop" },
    { id: "cyber-threat-hunting-workshop", title: "Cyber Threat Hunting Workshop" },
    { id: "corporate-law-workshop", title: "Corporate Law Workshop" },
    { id: "criminal-law-workshop", title: "Criminal Law Workshop" },
    { id: "finance-accounting-workshop", title: "Finance & Accounting Workshop" },
    { id: "human-resource-management-workshop", title: "Human Resource Management Workshop" },
    { id: "journalism-media-production-workshop", title: "Journalism & Media Production Workshop" },
    { id: "content-writing-copywriting-workshop", title: "Content Writing & Copywriting Workshop" },
    { id: "startup-innovation-workshop", title: "Startup & Innovation Workshop" }
];
