export const certificateDetails = {
    slNo: "029",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Aditya Kashyap",
    certificateHolderFirstName: "Aditya",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Kashyap",
    fatherSName: "G. P. Kashyap",
    fatherFirstName: "G.",
    fatherMiddleName: "P.",
    fatherLastName: "Kashyap",
    dateOfBirth: "18-May-2001",
    gender: "Male",
    certificateName: "Cyber Ethics Certificate",
    certificateType: "Professional Ethics Credential",
    courseQualificationName: "Responsible Vulnerability Disclosure, Privacy Rights & Cyber Ethics",
    institutionName: "CRCCF Cyber Ethics Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-CEC-2024-029",
    certificateNumber: "CERT-CEC-8929",
    issueDate: "05-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Grade A",
    certificateValidity: "Lifetime",
    issuingAuthority: "Ethics Committee Chairperson, CRCCF",
    mobileNumber: "+91 9876543129",
    emailId: "aditya.kashyap@example.com",
    address: "Gomti Nagar, Lucknow, Uttar Pradesh, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
