export const idCardDetails = {
    slNo: "005",
    idCardPhoto: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?fit=crop&w=800&q=80",
    name: "Dr. Arvind Swaminathan",
    firstName: "Arvind",
    middleName: "-",
    lastName: "Swaminathan",
    fatherSName: "K. Swaminathan",
    fatherFirstName: "K.",
    fatherMiddleName: "-",
    fatherLastName: "Swaminathan",
    dateOfBirth: "18-Jun-1975",
    gender: "Male",
    designation: "Executive Board Director",
    department: "Board of Governance & Strategic Directorate",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Board Director ID",
    employeeStudentMemberId: "CRCCF-DIR-005",
    idCardNumber: "IDC-2024-DIR05",
    issueDate: "01-Jan-2021",
    validFrom: "01-Jan-2021",
    expiryDate: "31-Dec-2030",
    mobileNumber: "+91 9900112233",
    emailId: "director@crccf.org",
    address: "CRCCF Headquarters, Vasant Kunj, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Unrestricted institutional access and executive signatory"
};
