export const employeeDetails = {
    slNo: "101",
    photo: "https://randomuser.me/api/portraits/men/32.jpg",
    name: "Subrajit",
    firstName: "Subrajit",
    middleName: "-",
    lastName: "-",
    fName: "Sanjay Kumar",
    fatherFirstName: "Sanjay",
    fatherMiddleName: "-",
    fatherLastName: "Kumar",
    dob: "15-Aug-1995",
    gender: "Male",
    designation: "Software Engineer",
    department: "IT",
    employeeCategory: "Technical",
    employeeType: "Full Time",
    dutyMode: "Office",
    employeeId: "009",
    joiningDate: "01-Sep-2022",
    mobileNumber: "+91 9876543210",
    mailId: "subrajit@example.com",
    address: "123, Tech Park Avenue, Block C, Bhubaneswar, India",
    status: "Active"
};
