export const idCardDetails = {
    slNo: "015",
    idCardPhoto: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?fit=crop&w=800&q=80",
    name: "Meenakshi Sundaram",
    firstName: "Meenakshi",
    middleName: "-",
    lastName: "Sundaram",
    fatherSName: "K. Sundaram",
    fatherFirstName: "K.",
    fatherMiddleName: "-",
    fatherLastName: "Sundaram",
    dateOfBirth: "19-Nov-1986",
    gender: "Female",
    designation: "Authorized Legal Representative",
    department: "External Affairs & Legal Representations",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Authorized Representative ID",
    employeeStudentMemberId: "CRCCF-REP-015",
    idCardNumber: "IDC-2024-REP15",
    issueDate: "15-Apr-2023",
    validFrom: "15-Apr-2023",
    expiryDate: "14-Apr-2026",
    mobileNumber: "+91 9444112233",
    emailId: "legal.rep@crccf.org",
    address: "High Court Chambers, Chennai, Tamil Nadu, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized to represent CRCCF in formal inter-agency proceedings"
};
