export const idCardDetails = {
    slNo: "035",
    idCardPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?fit=crop&w=800&q=80",
    name: "Shreya Nair",
    firstName: "Shreya",
    middleName: "-",
    lastName: "Nair",
    fatherSName: "G. Nair",
    fatherFirstName: "G.",
    fatherMiddleName: "-",
    fatherLastName: "Nair",
    dateOfBirth: "14-Feb-2002",
    gender: "Female",
    designation: "Chief Campus Ambassador",
    department: "Youth Cyber Literacy & Ambassador Cell",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Campus Ambassador ID",
    employeeStudentMemberId: "CRCCF-AMB-035",
    idCardNumber: "IDC-2024-AMB35",
    issueDate: "01-Sep-2023",
    validFrom: "01-Sep-2023",
    expiryDate: "31-Aug-2025",
    mobileNumber: "+91 9446223344",
    emailId: "shreya.nair@ambassadors.crccf.org",
    address: "Cochin University of Science & Technology, Kochi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized to conduct campus workshops and student cyber clubs"
};
