export const idCardDetails = {
    slNo: "014",
    idCardPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?fit=crop&w=800&q=80",
    name: "Justice Deepak Mishra",
    firstName: "Deepak",
    middleName: "-",
    lastName: "Mishra",
    fatherSName: "G. N. Mishra",
    fatherFirstName: "G.",
    fatherMiddleName: "N.",
    fatherLastName: "Mishra",
    dateOfBirth: "12-May-1960",
    gender: "Male",
    designation: "Apex Governing Council Member",
    department: "CRCCF Supreme Governing Council",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Governing Body ID",
    employeeStudentMemberId: "CRCCF-GOV-014",
    idCardNumber: "IDC-2024-GOV14",
    issueDate: "01-Jan-2021",
    validFrom: "01-Jan-2021",
    expiryDate: "31-Dec-2030",
    mobileNumber: "+91 9811003344",
    emailId: "governance@crccf.org",
    address: "Judicial Enclave, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Highest governance authority and legal oversight delegate"
};
