export const idCardDetails = {
    slNo: "019",
    idCardPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?fit=crop&w=800&q=80",
    name: "Varun Mehta",
    firstName: "Varun",
    middleName: "-",
    lastName: "Mehta",
    fatherSName: "K. K. Mehta",
    fatherFirstName: "K.",
    fatherMiddleName: "K.",
    fatherLastName: "Mehta",
    dateOfBirth: "28-Aug-1993",
    gender: "Male",
    designation: "Associate Research Member",
    department: "Applied Cryptography Forum",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Associate Member ID",
    employeeStudentMemberId: "CRCCF-ASC-019",
    idCardNumber: "IDC-2024-ASC19",
    issueDate: "01-Jan-2024",
    validFrom: "01-Jan-2024",
    expiryDate: "31-Dec-2025",
    mobileNumber: "+91 9821335577",
    emailId: "varun.mehta@crccf.org",
    address: "Bandra Kurla Complex, Mumbai, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Associate credential for research symposium access"
};
