export const certificateDetails = {
    slNo: "012",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Akash Deep Singh",
    certificateHolderFirstName: "Akash",
    certificateHolderMiddleName: "Deep",
    certificateHolderLastName: "Singh",
    fatherSName: "Harvinder Singh",
    fatherFirstName: "Harvinder",
    fatherMiddleName: "-",
    fatherLastName: "Singh",
    dateOfBirth: "30-Mar-1997",
    gender: "Male",
    certificateName: "Workshop Certificate",
    certificateType: "Hands-on Technical Workshop",
    courseQualificationName: "Malware Reverse Engineering & Dynamic Behavioral Sandbox Analysis",
    institutionName: "Advanced Cyber Threat Laboratory",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-WSC-2024-012",
    certificateNumber: "CERT-WSC-8912",
    issueDate: "14-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Distinction in Lab Exercises",
    certificateValidity: "Lifetime",
    issuingAuthority: "Workshop Coordinator, CRCCF",
    mobileNumber: "+91 9876543112",
    emailId: "akash.deep@example.com",
    address: "Model Town, Ludhiana, Punjab, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
