export const certificateDetails = {
    slNo: "013",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Tanvi Bhatia",
    certificateHolderFirstName: "Tanvi",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Bhatia",
    fatherSName: "Raman Bhatia",
    fatherFirstName: "Raman",
    fatherMiddleName: "-",
    fatherLastName: "Bhatia",
    dateOfBirth: "14-Aug-2001",
    gender: "Female",
    certificateName: "Participation Certificate",
    certificateType: "National Cyber Conclave Participation",
    courseQualificationName: "National Cyber Shield Defense Simulation & Tabletop Drill",
    institutionName: "CRCCF National Cyber Conclave",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-PC-2024-013",
    certificateNumber: "CERT-PC-8913",
    issueDate: "02-Dec-2024",
    passingYear: "2024",
    gradeMarks: "Active Delegate",
    certificateValidity: "Permanent Record",
    issuingAuthority: "Organizing Secretary, CRCCF",
    mobileNumber: "+91 9876543113",
    emailId: "tanvi.bhatia@example.com",
    address: "Civil Lines, Jaipur, Rajasthan, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
