export const certificateDetails = {
    slNo: "008",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Rajeshwar Rao",
    certificateHolderFirstName: "Rajeshwar",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Rao",
    fatherSName: "K. N. Rao",
    fatherFirstName: "K.",
    fatherMiddleName: "N.",
    fatherLastName: "Rao",
    dateOfBirth: "03-Feb-1988",
    gender: "Male",
    certificateName: "Professional Education Certificate",
    certificateType: "Executive Professional Education",
    courseQualificationName: "Executive Leadership in Cyber Risk & Resilience",
    institutionName: "Cyber Security Executive Education Institute",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-PEC-2024-008",
    certificateNumber: "CERT-PEC-8908",
    issueDate: "14-Aug-2024",
    passingYear: "2024",
    gradeMarks: "Executive Honor Roll",
    certificateValidity: "Lifetime",
    issuingAuthority: "Executive Director, CRCCF",
    mobileNumber: "+91 9876543108",
    emailId: "rajeshwar.rao@example.com",
    address: "Jubilee Hills, Hyderabad, Telangana, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
