export const bookDetails = {
    slNo: "Sample Sl No",
    bookCoverPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    bookTitle: "Sample Book Title",
    subtitle: "Sample Subtitle",
    authorName: "Sample Author Name",
    coAuthorName: "Sample Co-Author Name",
    publisherName: "Sample Publisher Name",
    edition: "Sample Edition",
    isbnNumber: "Sample ISBN Number",
    bookType: "Sample Book Type",
    category: "Sample Category",
    language: "Sample Language",
    publicationDate: "Sample Publication Date",
    numberOfPages: "Sample Number of Pages",
    volumeNumber: "Sample Volume Number",
    copyrightHolder: "Sample Copyright Holder",
    copyrightYear: "Sample Copyright Year",
    registrationNumber: "Sample Registration Number",
    publisherAddress: "Sample Publisher Address",
    publisherEmail: "Sample Publisher Email",
    publisherMobile: "Sample Publisher Mobile",
    bookStatus: "Sample Book Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};