export const certificateDetails = {
    slNo: "030",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Arjun Nambisan",
    certificateHolderFirstName: "Arjun",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Nambisan",
    fatherSName: "K. Nambisan",
    fatherFirstName: "K.",
    fatherMiddleName: "-",
    fatherLastName: "Nambisan",
    dateOfBirth: "23-Feb-1997",
    gender: "Male",
    certificateName: "AI & Cyber Security Certificate",
    certificateType: "Advanced Specialized Certification",
    courseQualificationName: "AI-Powered Threat Detection & Large Language Model Defense",
    institutionName: "CRCCF Center for Artificial Intelligence",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-ACSC-2024-030",
    certificateNumber: "CERT-ACSC-8930",
    issueDate: "15-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Head of AI Defense, CRCCF",
    mobileNumber: "+91 9876543130",
    emailId: "arjun.nambisan@example.com",
    address: "HSR Layout, Bengaluru, Karnataka, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
