export const idCardDetails = {
    slNo: "028",
    idCardPhoto: "https://images.unsplash.com/photo-1580489944761-15a19d654956?fit=crop&w=800&q=80",
    name: "Prof. Gayatri Venkat",
    firstName: "Gayatri",
    middleName: "-",
    lastName: "Venkat",
    fatherSName: "T. Venkatraman",
    fatherFirstName: "T.",
    fatherMiddleName: "-",
    fatherLastName: "Venkatraman",
    dateOfBirth: "06-Jul-1979",
    gender: "Female",
    designation: "Head of Digital Forensics Faculty",
    department: "School of Cyber Forensics & Law",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Academic Faculty ID",
    employeeStudentMemberId: "CRCCF-FAC-028",
    idCardNumber: "IDC-2024-FAC28",
    issueDate: "01-Jan-2021",
    validFrom: "01-Jan-2021",
    expiryDate: "31-Dec-2026",
    mobileNumber: "+91 9444009988",
    emailId: "prof.gayatri@crccf.org",
    address: "Faculty Residences, Anna University, Chennai, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Dean of Academic Research and curriculum director"
};
