export const ROUTES = {
  HOMEPAGE: '/homepage',
  GALLERY_COLLECTIONS: '/gallery-collections',
  GALLERY: '/gallery',
  GALLERY_CATEGORY_ID: '/gallery/category/:id',
  REACHUS: '/reachus',
  INSIGHTS: '/insights',
  SOFTWARE_PRODUCTS: '/software-products',
  SERVICES: '/services/*',
  REPORT_CRIME: '/report-crime',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT: '/report-crime/victim-rights-support',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_RIGHT_OF_CYBERCRIME_VICTIMS: '/report-crime/victim-rights-support/right-of-cybercrime-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_VICTIM_ASSISTANCE_PROTECTION: '/report-crime/victim-rights-support/victim-assistance-protection',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_CYBERCRIME_VICTIM_RIGHTS_RELIEF: '/report-crime/victim-rights-support/cybercrime-victim-rights-relief',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_DIGITAL_CRIME_VICTIM_HELP_DESK: '/report-crime/victim-rights-support/digital-crime-victim-help-desk',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_SUPPORT_SERVICES_FOR_VICTIMS: '/report-crime/victim-rights-support/support-services-for-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_HELP_JUSTICE_FOR_VICTIMS: '/report-crime/victim-rights-support/help-justice-for-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_EMPOWERING_CYBERCRIME_VICTIMS: '/report-crime/victim-rights-support/empowering-cybercrime-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_DIGITAL_VICTIM_SUPPORT_PROTECTION: '/report-crime/victim-rights-support/digital-victim-support-protection',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_VICTIM_PROTECTION_LEGAL_AID: '/report-crime/victim-rights-support/victim-protection-legal-aid',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_ONLINE_HARASSMENT_HELP_RIGHTS: '/report-crime/victim-rights-support/online-harassment-help-rights',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_CYBER_JUSTICE_FOR_VICTIMS: '/report-crime/victim-rights-support/cyber-justice-for-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_CYBERCRIME_VICTIM_ADVOCACY: '/report-crime/victim-rights-support/cybercrime-victim-advocacy',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_ONLINE_SAFETY_VICTIM_HELP: '/report-crime/victim-rights-support/online-safety-victim-help',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_JUSTICE_HEALING_FOR_VICTIMS: '/report-crime/victim-rights-support/justice-healing-for-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_RESTORING_DIGNITY_TO_CYBER_VICTIMS: '/report-crime/victim-rights-support/restoring-dignity-to-cyber-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_DIGITAL_JUSTICE_SUPPORT_SERVICES: '/report-crime/victim-rights-support/digital-justice-support-services',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_VICTIM_OUTREACH_LEGAL_SUPPORT: '/report-crime/victim-rights-support/victim-outreach-legal-support',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_PSYCHOLOGICAL_COUNSELLING_FOR_CYBER_VICTIMS: '/report-crime/victim-rights-support/psychological-counselling-for-cyber-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_VICTIM_HELPLINE_CHAT_SUPPORT: '/report-crime/victim-rights-support/victim-helpline-chat-support',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_WOMEN_CHILD_CYBER_SAFETY_SUPPORT: '/report-crime/victim-rights-support/women-child-cyber-safety-support',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_LEGAL_GUIDANCE_FOR_DIGITAL_CRIME_VICTIMS: '/report-crime/victim-rights-support/legal-guidance-for-digital-crime-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_DATA_PRIVACY_PROTECTION_SUPPORT: '/report-crime/victim-rights-support/data-privacy-protection-support',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_SOCIAL_MEDIA_MISUSE_VICTIM_AID: '/report-crime/victim-rights-support/social-media-misuse-victim-aid',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_PHISHING_ONLINE_SCAM_VICTIM_SUPPORT: '/report-crime/victim-rights-support/phishing-online-scam-victim-support',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_CYBER_EXTORTION_BLACKMAIL_RESPONSE_TEAM: '/report-crime/victim-rights-support/cyber-extortion-blackmail-response-team',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_DIGITAL_FORENSICS_ASSISTANCE_FOR_VICTIMS: '/report-crime/victim-rights-support/digital-forensics-assistance-for-victims',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_EDUCATIONAL_RESOURCES_FOR_VICTIM_RIGHTS: '/report-crime/victim-rights-support/educational-resources-for-victim-rights',
  REPORT_CRIME_VICTIM_RIGHTS_SUPPORT_CYBER_VICTIM_RELIEF_EMERGENCY_RESPONSE: '/report-crime/victim-rights-support/cyber-victim-relief-emergency-response',
  REPORT_CRIME_CYBER_SECURITY_TIPS: '/report-crime/cyber-security-tips',
  REPORT_CRIME_AWARENESS_PREVENTION_TIPS: '/report-crime/awareness-prevention-tips',
  REPORT_CRIME_CYBER_SAFETY_WOMEN: '/report-crime/cyber-safety-women',
  REPORT_CRIME_LEGAL_GUIDANCE_AWARENESS: '/report-crime/legal-guidance-awareness',
  REPORT_CRIME_CYBER_LAWS_AND_RIGHTS: '/report-crime/cyber-laws-and-rights',
  SOFTWARE_PRODUCTS_DEVELOPED_SOFTWARE_PRODUCTS: '/software-products/developed-software-products',
  SOFTWARE_PRODUCTS_PRODUCTS_UNDER_DEVELOPMENT: '/software-products/products-under-development',
  SOFTWARE_PRODUCTS_UPCOMING_SOFTWARE_INNOVATIONS: '/software-products/upcoming-software-innovations',
  SOFTWARE_PRODUCTS_CYBER_SECURITY_SOFTWARE_SOLUTIONS: '/software-products/cyber-security-software-solutions',
  SOFTWARE_PRODUCTS_AI_AUTOMATION_PRODUCTS: '/software-products/ai-automation-products',
  SOFTWARE_PRODUCTS_MOBILE_APPLICATION_PRODUCTS: '/software-products/mobile-application-products',
  SOFTWARE_PRODUCTS_WEB_BASED_DIGITAL_PLATFORMS: '/software-products/web-based-digital-platforms',
  SOFTWARE_PRODUCTS_ENTERPRISE_SOFTWARE_SOLUTIONS: '/software-products/enterprise-software-solutions',
  SOFTWARE_PRODUCTS_EDUCATIONAL_TECHNOLOGY_PRODUCTS: '/software-products/educational-technology-products',
  SOFTWARE_PRODUCTS_DATA_ANALYTICS_REPORTING_TOOLS: '/software-products/data-analytics-reporting-tools',
  SOFTWARE_PRODUCTS_CLOUD_BASED_SOFTWARE_SOLUTIONS: '/software-products/cloud-based-software-solutions',
  SOFTWARE_PRODUCTS_RESEARCH_DEVELOPMENT_PRODUCTS: '/software-products/research-development-products',
  SOFTWARE_PRODUCTS_CYBER_CRIME_INVESTIGATION_SOFTWARE: '/software-products/cyber-crime-investigation-software',
  SOFTWARE_PRODUCTS_CYBER_SECURITY_SOFTWARE: '/software-products/cyber-security-software',
  SOFTWARE_PRODUCTS_CYBER_CRIME_AWARENESS_SOFTWARE: '/software-products/cyber-crime-awareness-software',
  SOFTWARE_PRODUCTS_CYBER_CRIME_VICTIM_SUPPORT_SOFTWARE: '/software-products/cyber-crime-victim-support-software',
  SOFTWARE_PRODUCTS_CASE_TRACKING_SOFTWARE: '/software-products/case-tracking-software',
  SOFTWARE_PRODUCTS_CYBER_INTELLIGENCE_SOFTWARE: '/software-products/cyber-intelligence-software',
  SOFTWARE_PRODUCTS_DIGITAL_FORENSIC_SUPPORT_TOOLS: '/software-products/digital-forensic-support-tools',
  SOFTWARE_PRODUCTS_TRAINING_INTERNSHIP_MANAGEMENT_SOFTWARE: '/software-products/training-internship-management-software',
  SOFTWARE_PRODUCTS_USER_SUPPORT_HELPDESK_SOFTWARE: '/software-products/user-support-helpdesk-software',
  SOFTWARE_PRODUCTS_HR_RECRUITMENT_MANAGEMENT_SOFTWARE: '/software-products/hr-recruitment-management-software',
  SOFTWARE_PRODUCTS_REPORT_GENERATION_SOFTWARE: '/software-products/report-generation-software',
  SOFTWARE_PRODUCTS_SOFTWARE_PRODUCT_OVERVIEW: '/software-products/software-product-overview',
  SKILL_DEVELOPMENT: '/skill-development',
  SKILL_DEVELOPMENT_INTERNSHIPS: '/skill-development/internships',
  SKILL_DEVELOPMENT_COURSES: '/skill-development/courses/*',
  INTERNSHIP_ID: '/internship/:id',
  SKILL_DEVELOPMENT_PLACEMENT: '/skill-development/placement',
  SKILL_DEVELOPMENT_CAREER: '/skill-development/career',
  SKILL_DEVELOPMENT_AWARENESS: '/skill-development/awareness',
  SKILL_DEVELOPMENT_MENTORSHIP: '/skill-development/mentorship/*',
  SKILL_DEVELOPMENT_RESEARCH: '/skill-development/research/*',
  SKILL_DEVELOPMENT_CORPORATE: '/skill-development/corporate/*',
  SKILL_DEVELOPMENT_HACKATHONS: '/skill-development/hackathons/*',
  SKILL_DEVELOPMENT_WORKSHOPS: '/skill-development/workshops/*',
  SKILL_DEVELOPMENT_TRAINING: '/skill-development/training/*',
  SKILL_DEVELOPMENT_SLUG: '/skill-development/:slug',
  RESOURCES_COURSE_MATERIALS: '/resources/course-materials',
  RESOURCES_PRACTICAL_TRAINING: '/resources/practical-training',
  RESOURCES_MENTORSHIP_EVALUATION: '/resources/mentorship-evaluation',
  RESOURCES_LEARNING_ENVIRONMENT: '/resources/learning-environment',
  ABOUT: '/about',
  IDENTITY: 'identity',
  INTRODUCTION: 'introduction',
  WHAT_WE_DO: 'what-we-do',
  MISSION_VISION: 'mission-vision',
  ACTIVITY: 'activity',
  PURPOSE: 'purpose',
  OBJECTIVE: 'objective',
  ACHIEVEMENT: 'achievement',
  LEGAL_COMPLIANCE: 'legal-compliance/*',
  PRIVACY_POLICY: 'privacy-policy',
  DATA_PROTECTION: 'data-protection',
  TERMS_CONDITIONS: 'terms-conditions',
  RULES_REGULATION: 'rules-regulation',
  INSTRUCTION: 'instruction',
  LEGAL_DISCLAIMER: 'legal-disclaimer',
  COPYRIGHT: 'copyright',
  PARTNERSHIP: 'partnership',
  HISTORY: 'history',
  CAREERS: '/careers',
  RECRUITMENT: '/recruitment',
  RECRUITMENT_JOB_VACANCY: '/recruitment/job-vacancy',
  RECRUITMENT_JOB_VACANCY_DETAILS: '/recruitment/job-vacancy-details',
  RECRUITMENT_CURRENT_VACANCY: '/recruitment/current-vacancy',
  RECRUITMENT_CURRENT_VACANCY_JOB_VACANCY: '/recruitment/current-vacancy/job-vacancy',
  RECRUITMENT_CURRENT_VACANCY_JOB_VACANCY_NEW_REGISTRATION: '/recruitment/current-vacancy/job-vacancy/new-registration',
  RECRUITMENT_JOB_VACANCY_NEW_REGISTRATION: '/recruitment/job-vacancy/new-registration',
  RECRUITMENT_CURRENT_VACANCY_POST_VACANCY: '/recruitment/current-vacancy/post-vacancy',
  RECRUITMENT_CURRENT_VACANCY_INTERNSHIP_VACANCY: '/recruitment/current-vacancy/internship-vacancy',
  RECRUITMENT_CURRENT_VACANCY_VACANCY_CARD_1: '/recruitment/current-vacancy/vacancy-card-1',
  RECRUITMENT_CURRENT_VACANCY_VACANCY_CARD_2: '/recruitment/current-vacancy/vacancy-card-2',
  RECRUITMENT_CURRENT_VACANCY_VACANCY_CARD_3: '/recruitment/current-vacancy/vacancy-card-3',
  RECRUITMENT_CURRENT_VACANCY_VACANCY_CARD_4: '/recruitment/current-vacancy/vacancy-card-4',
  RECRUITMENT_CURRENT_VACANCY_VACANCY_CARD_5: '/recruitment/current-vacancy/vacancy-card-5',
  RECRUITMENT_DOCUMENT_VERIFICATION_DEPARTMENT: '/recruitment/document-verification-department',
  RECRUITMENT_ONLINE_APPLICATION_PORTAL: '/recruitment/online-application-portal',
  RECRUITMENT_ADVERTISEMENTS: '/recruitment/advertisements',
  RECRUITMENT_PRESS_RELEASE_NOTICES: '/recruitment/press-release-notices',
  RECRUITMENT_APPLICATION_STATUS: '/recruitment/application-status',
  RECRUITMENT_SUBMIT_RESUME: '/recruitment/submit-resume',
  RECRUITMENT_CERTIFICATE_VERIFICATION: '/recruitment/certificate-verification',
  RECRUITMENT_CERTIFICATE_VERIFICATION_SLUG: '/recruitment/certificate-verification/:slug',
  RECRUITMENT_ID_CARD_VERIFICATION: '/recruitment/id-card-verification',
  RECRUITMENT_RULES_POLICIES: '/recruitment/rules-policies',
  COMING_SOON: '/coming-soon',
  ABOUT_INDEX: '/about',
};

export const ROUTE_METADATA = [
  { path: '/homepage', title: 'Home', description: 'CR Cyber Crime Foundation provides cyber security, cyber awareness, cyber investigation, digital safety services, training, consultancy, and digital empowerment.' },
  { path: '/gallery-collections', title: 'Gallery Collections', description: 'View our gallery collections of events, workshops, and cyber awareness programs conducted by CR Cyber Crime Foundation.' },
  { path: '/gallery', title: 'Gallery', description: 'Explore our gallery featuring photos from various cyber security awareness campaigns and training programs.' },
  { path: '/gallery/category/:id', title: 'Gallery Category', description: 'Browse specific categories of our cyber security events and training gallery.' },
  { path: '/reachus', title: 'Reach Us', description: 'Contact CR Cyber Crime Foundation for cyber security consultancy, training, and cyber crime investigation services.' },
  { path: '/insights', title: 'Insights', description: 'Read our latest insights, articles, and research on cyber security, digital safety, and cyber crime prevention.' },
  { path: '/software-products', title: 'Software Products', description: 'Explore our advanced software products and IT solutions designed for robust cyber security and digital infrastructure.' },
  { path: '/services/*', title: 'Our Services', description: 'Comprehensive cyber security, digital marketing, IT support, and legal services offered by CRCCF.' },
  { path: '/report-crime', title: 'Report Cyber Crime', description: 'Report cyber crime incidents securely. Get assistance with FIR filing, digital evidence collection, and legal support.' },
  { path: '/report-crime/victim-rights-support', title: 'Victim Rights & Support', description: 'Learn about victim rights, emotional support, and legal assistance provided by CRCCF for victims of cyber crime.' },
  { path: '/report-crime/victim-rights-support/right-of-cybercrime-victims', title: 'Right of Cybercrime Victims', description: 'Right of Cybercrime Victims' },
  { path: '/report-crime/victim-rights-support/victim-assistance-protection', title: 'Victim Assistance & Protection', description: 'Victim Assistance & Protection' },
  { path: '/report-crime/victim-rights-support/cybercrime-victim-rights-relief', title: 'Cybercrime Victim Rights & Relief', description: 'Cybercrime Victim Rights & Relief' },
  { path: '/report-crime/victim-rights-support/digital-crime-victim-help-desk', title: 'Digital Crime Victim Help Desk', description: 'Digital Crime Victim Help Desk' },
  { path: '/report-crime/victim-rights-support/support-services-for-victims', title: 'Support Services for Victims', description: 'Support Services for Victims' },
  { path: '/report-crime/victim-rights-support/help-justice-for-victims', title: 'Help & Justice for Victims', description: 'Help & Justice for Victims' },
  { path: '/report-crime/victim-rights-support/empowering-cybercrime-victims', title: 'Empowering Cybercrime Victims', description: 'Empowering Cybercrime Victims' },
  { path: '/report-crime/victim-rights-support/digital-victim-support-protection', title: 'Digital Victim Support & Protection', description: 'Digital Victim Support & Protection' },
  { path: '/report-crime/victim-rights-support/victim-protection-legal-aid', title: 'Victim Protection & Legal Aid', description: 'Victim Protection & Legal Aid' },
  { path: '/report-crime/victim-rights-support/online-harassment-help-rights', title: 'Online Harassment Help & Rights', description: 'Online Harassment Help & Rights' },
  { path: '/report-crime/victim-rights-support/cyber-justice-for-victims', title: 'Cyber Justice for Victims', description: 'Cyber Justice for Victims' },
  { path: '/report-crime/victim-rights-support/cybercrime-victim-advocacy', title: 'Cybercrime Victim Advocacy', description: 'Cybercrime Victim Advocacy' },
  { path: '/report-crime/victim-rights-support/online-safety-victim-help', title: 'Online Safety & Victim Help', description: 'Online Safety & Victim Help' },
  { path: '/report-crime/victim-rights-support/justice-healing-for-victims', title: 'Justice & Healing for Victims', description: 'Justice & Healing for Victims' },
  { path: '/report-crime/victim-rights-support/restoring-dignity-to-cyber-victims', title: 'Restoring Dignity to Cyber Victims', description: 'Restoring Dignity to Cyber Victims' },
  { path: '/report-crime/victim-rights-support/digital-justice-support-services', title: 'Digital Justice Support Services', description: 'Digital Justice Support Services' },
  { path: '/report-crime/victim-rights-support/victim-outreach-legal-support', title: 'Victim Outreach & Legal Support', description: 'Victim Outreach & Legal Support' },
  { path: '/report-crime/victim-rights-support/psychological-counselling-for-cyber-victims', title: 'Psychological Counselling for Cyber Victims', description: 'Psychological Counselling for Cyber Victims' },
  { path: '/report-crime/victim-rights-support/victim-helpline-chat-support', title: '24/7 Victim Helpline & Chat Support', description: '24/7 Victim Helpline & Chat Support' },
  { path: '/report-crime/victim-rights-support/women-child-cyber-safety-support', title: 'Women & Child Cyber Safety Support', description: 'Women & Child Cyber Safety Support' },
  { path: '/report-crime/victim-rights-support/legal-guidance-for-digital-crime-victims', title: 'Legal Guidance for Digital Crime Victims', description: 'Legal Guidance for Digital Crime Victims' },
  { path: '/report-crime/victim-rights-support/data-privacy-protection-support', title: 'Data Privacy & Protection Support', description: 'Data Privacy & Protection Support' },
  { path: '/report-crime/victim-rights-support/social-media-misuse-victim-aid', title: 'Social Media Misuse Victim Aid', description: 'Social Media Misuse Victim Aid' },
  { path: '/report-crime/victim-rights-support/phishing-online-scam-victim-support', title: 'Phishing & Online Scam Victim Support', description: 'Phishing & Online Scam Victim Support' },
  { path: '/report-crime/victim-rights-support/cyber-extortion-blackmail-response-team', title: 'Cyber Extortion & Blackmail Response Team', description: 'Cyber Extortion & Blackmail Response Team' },
  { path: '/report-crime/victim-rights-support/digital-forensics-assistance-for-victims', title: 'Digital Forensics Assistance for Victims', description: 'Digital Forensics Assistance for Victims' },
  { path: '/report-crime/victim-rights-support/educational-resources-for-victim-rights', title: 'Educational Resources for Victim Rights', description: 'Educational Resources for Victim Rights' },
  { path: '/report-crime/victim-rights-support/cyber-victim-relief-emergency-response', title: 'Cyber Victim Relief & Emergency Response', description: 'Cyber Victim Relief & Emergency Response' },
  { path: '/report-crime/cyber-security-tips', title: 'Cyber Security Tips', description: 'Cyber Security Tips and Guidelines from CR Cyber Crime Foundation.' },
  { path: '/report-crime/awareness-prevention-tips', title: 'Awareness & Prevention Tips', description: 'Learn important cyber security awareness and prevention tips from CR Cyber Crime Foundation.' },
  { path: '/report-crime/cyber-safety-women', title: 'Cyber Safety & Support for Girls and Women', description: 'Learn about cyber safety and support for girls and women.' },
  { path: '/report-crime/legal-guidance-awareness', title: 'Legal Guidance & Awareness', description: 'Legal Guidance and Awareness.' },
  { path: '/report-crime/cyber-laws-and-rights', title: 'Cyber Laws & Rights', description: 'Learn about cyber laws and your digital rights.' },
  { path: '/software-products/developed-software-products', title: 'Developed Software Products', description: 'Developed Software Products details.' },
  { path: '/software-products/products-under-development', title: 'Products Under Development', description: 'Products Under Development details.' },
  { path: '/software-products/upcoming-software-innovations', title: 'Upcoming Software Innovations', description: 'Upcoming Software Innovations details.' },
  { path: '/software-products/cyber-security-software-solutions', title: 'Cyber Security Software Solutions', description: 'Cyber Security Software Solutions details.' },
  { path: '/software-products/ai-automation-products', title: 'AI & Automation Products', description: 'AI & Automation Products details.' },
  { path: '/software-products/mobile-application-products', title: 'Mobile Application Products', description: 'Mobile Application Products details.' },
  { path: '/software-products/web-based-digital-platforms', title: 'Web-Based Digital Platforms', description: 'Web-Based Digital Platforms details.' },
  { path: '/software-products/enterprise-software-solutions', title: 'Enterprise Software Solutions', description: 'Enterprise Software Solutions details.' },
  { path: '/software-products/educational-technology-products', title: 'Educational Technology Products', description: 'Educational Technology Products details.' },
  { path: '/software-products/data-analytics-reporting-tools', title: 'Data Analytics & Reporting Tools', description: 'Data Analytics & Reporting Tools details.' },
  { path: '/software-products/cloud-based-software-solutions', title: 'Cloud-Based Software Solutions', description: 'Cloud-Based Software Solutions details.' },
  { path: '/software-products/research-development-products', title: 'Research & Development Products', description: 'Research & Development Products details.' },
  { path: '/software-products/cyber-crime-investigation-software', title: 'Cyber Crime Investigation Software', description: 'Cyber Crime Investigation Software details.' },
  { path: '/software-products/cyber-security-software', title: 'Cyber Security Software', description: 'Cyber Security Software details.' },
  { path: '/software-products/cyber-crime-awareness-software', title: 'Cyber Crime Awareness Software', description: 'Cyber Crime Awareness Software details.' },
  { path: '/software-products/cyber-crime-victim-support-software', title: 'Cyber Crime Victim Support Software', description: 'Cyber Crime Victim Support Software details.' },
  { path: '/software-products/case-tracking-software', title: 'Case Tracking Software', description: 'Case Tracking Software details.' },
  { path: '/software-products/cyber-intelligence-software', title: 'Cyber Intelligence Software', description: 'Cyber Intelligence Software details.' },
  { path: '/software-products/digital-forensic-support-tools', title: 'Digital Forensic Support Tools', description: 'Digital Forensic Support Tools details.' },
  { path: '/software-products/training-internship-management-software', title: 'Training & Internship Management Software', description: 'Training & Internship Management Software details.' },
  { path: '/software-products/user-support-helpdesk-software', title: 'User Support & Helpdesk Software', description: 'User Support & Helpdesk Software details.' },
  { path: '/software-products/hr-recruitment-management-software', title: 'HR & Recruitment Management Software', description: 'HR & Recruitment Management Software details.' },
  { path: '/software-products/report-generation-software', title: 'Police Investigation Tools & Software', description: 'Police Investigation Tools & Software details.' },
  { path: '/software-products/software-product-overview', title: 'Software Product Overview', description: 'Software Product Overview details.' },
  { path: '/skill-development', title: 'Skill Development', description: 'Enhance your cyber security skills with our training programs, internships, courses, and workshops.' },
  { path: '/skill-development/internships', title: 'Internship Programs', description: 'Join our cyber security internship programs to gain hands-on experience in digital investigation and IT security.' },
  { path: '/skill-development/courses/*', title: 'Cyber Security Courses', description: 'Enroll in our specialized courses to learn ethical hacking, cyber forensics, and IT development.' },
  { path: '/internship/:id', title: 'Internship Details', description: 'Detailed information about our cyber security and IT internship opportunities.' },
  { path: '/skill-development/placement', title: 'Talent Placement Program', description: 'Our talent placement program connects trained cyber security professionals with top industry organizations.' },
  { path: '/skill-development/career', title: 'Career Guidance', description: 'Get expert career guidance in cyber security, ethical hacking, and IT development.' },
  { path: '/skill-development/awareness', title: 'Awareness Programs', description: 'Participate in our cyber awareness programs to learn how to stay safe in the digital world.' },
  { path: '/skill-development/mentorship/*', title: 'Mentorship Programs', description: 'Connect with industry experts through our cyber security mentorship programs.' },
  { path: '/skill-development/research/*', title: 'Research & Development', description: 'Explore our research and development initiatives in cyber security and digital forensics.' },
  { path: '/skill-development/corporate/*', title: 'Corporate Training', description: 'Customized corporate training programs to build robust cyber security knowledge within your organization.' },
  { path: '/skill-development/hackathons/*', title: 'Hackathons', description: 'Participate in CRCCF hackathons to solve real-world cyber security challenges.' },
  { path: '/skill-development/workshops/*', title: 'Workshops', description: 'Join expert-led workshops on cybersecurity and IT.' },
  { path: '/skill-development/training/*', title: 'Training Programs', description: 'Comprehensive training programs covering various aspects of cyber security and digital investigation.' },
  { path: '/skill-development/:slug', title: 'Skill Development Details', description: 'Explore specific skill development opportunities in cyber security and IT.' },
  { path: '/resources/course-materials', title: 'Course Materials', description: 'Access comprehensive course materials for our cyber security and IT training programs.' },
  { path: '/resources/practical-training', title: 'Practical Training', description: 'Engage in hands-on practical training to build real-world cyber security skills.' },
  { path: '/resources/mentorship-evaluation', title: 'Mentorship Evaluation', description: 'Evaluate and track your progress in our cyber security mentorship programs.' },
  { path: '/resources/learning-environment', title: 'Learning Environment', description: 'Discover our state-of-the-art learning environment designed for optimal cyber security education.' },
  { path: '/about', title: 'About Us', description: 'Learn about CR Cyber Crime Foundation, our mission, vision, and core activities in cyber security.' },
  { path: 'identity', title: 'Identity', description: 'CR Cyber Crime Foundation Identity page.' },
  { path: 'introduction', title: 'Introduction', description: 'CR Cyber Crime Foundation Introduction page.' },
  { path: 'what-we-do', title: 'What We Do', description: 'CR Cyber Crime Foundation What We Do page.' },
  { path: 'mission-vision', title: 'Mission Vision', description: 'CR Cyber Crime Foundation Mission Vision page.' },
  { path: 'activity', title: 'Activity', description: 'CR Cyber Crime Foundation Activity page.' },
  { path: 'purpose', title: 'Purpose', description: 'CR Cyber Crime Foundation Purpose page.' },
  { path: 'objective', title: 'Objective', description: 'CR Cyber Crime Foundation Objective page.' },
  { path: 'achievement', title: 'Achievement', description: 'CR Cyber Crime Foundation Achievement page.' },
  { path: 'legal-compliance/*', title: '*', description: 'CR Cyber Crime Foundation * page.' },
  { path: 'privacy-policy', title: 'Privacy Policy', description: 'CR Cyber Crime Foundation Privacy Policy page.' },
  { path: 'data-protection', title: 'Meaning Behind Our Name', description: 'CR Cyber Crime Foundation Meaning Behind Our Name page.' },
  { path: 'terms-conditions', title: 'Terms Conditions', description: 'CR Cyber Crime Foundation Terms Conditions page.' },
  { path: 'rules-regulation', title: 'Rules Regulation', description: 'CR Cyber Crime Foundation Rules Regulation page.' },
  { path: 'instruction', title: 'Instruction', description: 'CR Cyber Crime Foundation Instruction page.' },
  { path: 'legal-disclaimer', title: 'Legal Disclaimer', description: 'CR Cyber Crime Foundation Legal Disclaimer page.' },
  { path: 'copyright', title: 'Copyright', description: 'CR Cyber Crime Foundation Copyright page.' },
  { path: 'partnership', title: 'Partnership', description: 'CR Cyber Crime Foundation Partnership page.' },
  { path: 'history', title: 'History', description: 'CR Cyber Crime Foundation History page.' },
  { path: '/careers', title: 'Careers', description: 'Explore career opportunities and job vacancies at CR Cyber Crime Foundation.' },
  { path: '/recruitment', title: 'Recruitment Portal', description: 'Access our recruitment portal for job applications and career opportunities.' },
  { path: '/recruitment/job-vacancy', title: 'Job Vacancies', description: 'View current job vacancies and openings at CRCCF.' },
  { path: '/recruitment/job-vacancy-details', title: 'Job Vacancy Details', description: 'Detailed information about specific job vacancies at CRCCF.' },
  { path: '/recruitment/current-vacancy', title: 'Current Vacancies', description: 'View current job vacancies.' },
  { path: '/recruitment/current-vacancy/job-vacancy', title: 'Job Vacancy', description: 'Job Vacancy details.' },
  { path: '/recruitment/current-vacancy/job-vacancy/new-registration', title: 'Candidate Master Profile - New Registration', description: 'Register candidate master profile for CRCCF job vacancies.' },
  { path: '/recruitment/job-vacancy/new-registration', title: 'Candidate Master Profile - New Registration', description: 'Register candidate master profile for CRCCF job vacancies.' },
  { path: '/recruitment/current-vacancy/post-vacancy', title: 'Post Vacancy', description: 'Post Vacancy details.' },
  { path: '/recruitment/current-vacancy/internship-vacancy', title: 'Internship Vacancy', description: 'Internship Vacancy details.' },
  { path: '/recruitment/current-vacancy/vacancy-card-1', title: 'Vacancy Card 1', description: 'Vacancy Card 1 details.' },
  { path: '/recruitment/current-vacancy/vacancy-card-2', title: 'Vacancy Card 2', description: 'Vacancy Card 2 details.' },
  { path: '/recruitment/current-vacancy/vacancy-card-3', title: 'Vacancy Card 3', description: 'Vacancy Card 3 details.' },
  { path: '/recruitment/current-vacancy/vacancy-card-4', title: 'Vacancy Card 4', description: 'Vacancy Card 4 details.' },
  { path: '/recruitment/current-vacancy/vacancy-card-5', title: 'Vacancy Card 5', description: 'Vacancy Card 5 details.' },
  { path: '/recruitment/document-verification-department', title: 'Document Verification Department', description: 'Exclusive portal for members to post job vacancies.' },
  { path: '/recruitment/online-application-portal', title: 'Online Application Portal', description: 'Submit your job applications online through our dedicated portal.' },
  { path: '/recruitment/advertisements', title: 'Recruitment Advertisements', description: 'View our latest recruitment advertisements and notices.' },
  { path: '/recruitment/press-release-notices', title: 'Press Releases & Notices', description: 'Read official press releases and notices related to recruitment.' },
  { path: '/recruitment/application-status', title: 'Application Status', description: 'Check the status of your submitted job applications.' },
  { path: '/recruitment/submit-resume', title: 'Submit Resume', description: 'Submit your resume for future career opportunities with CRCCF.' },
  { path: '/recruitment/certificate-verification', title: 'Certificate Verification', description: 'Verify the authenticity of certificates issued by CR Cyber Crime Foundation.' },
  { path: '/recruitment/certificate-verification/:slug', title: 'Certificate Verification Details', description: 'Detailed certificate verification portal.' },
  { path: '/recruitment/id-card-verification', title: 'ID Card Verification', description: 'Verify the authenticity of ID cards.' },
  { path: '/recruitment/rules-policies', title: 'Recruitment Rules & Policies', description: 'Read the comprehensive rules and policies governing our recruitment process.' },
  { path: '/coming-soon', title: 'Coming Soon', description: 'This section is currently under development.' },
  { path: '/about', title: 'Dashboard', description: 'CR Cyber Crime Foundation Dashboard' },
];
