export const volunteerDetails = {
    slNo: "Sample Sl No",
    volunteerPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    volunteerName: "Sample Volunteer Name",
    fatherSName: "Sample Father's Name",
    dateOfBirth: "Sample Date of Birth",
    gender: "Sample Gender",
    occupation: "Sample Occupation",
    volunteerId: "Sample Volunteer ID",
    volunteerRegistrationId: "Sample Volunteer Registration ID",
    volunteerCategory: "Sample Volunteer Category",
    volunteerType: "Sample Volunteer Type",
    department: "Sample Department",
    organization: "Sample Organization",
    areaOfService: "Sample Area of Service",
    volunteerRole: "Sample Volunteer Role",
    joiningDate: "Sample Joining Date",
    serviceStartDate: "Sample Service Start Date",
    serviceEndDate: "Sample Service End Date",
    validity: "Sample Validity",
    volunteerHours: "Sample Volunteer Hours",
    mobileNumber: "Sample Mobile Number",
    emailId: "Sample Email ID",
    address: "Sample Address",
    volunteerStatus: "Sample Volunteer Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};