import branchesData from "../../../../data/Contact/branchesData";

export const branchDetailsData = {
  branches: branchesData,
  constants: {
    autoBranchRotationMs: 6000,
    activeMarkerColor: [255 / 255, 101 / 255, 36 / 255],
    defaultMarkerColor: [2 / 255, 156 / 255, 255 / 255],
    clusterOffsets: [
      [0, 0],
      [0.45, 0.72],
      [-0.45, -0.72],
      [0.72, -0.45],
      [-0.72, 0.45],
      [1.05, 0.25],
      [-1.05, -0.25],
      [0.25, -1.05],
      [-0.25, 1.05],
    ],
    locationHints: [
      {
        keys: ["bbsr", "bhubaneswar"],
        displayCity: "Bhubaneswar",
        displayState: "Odisha",
        country: "India",
        region: "East India",
        latitude: 20.2961,
        longitude: 85.8245,
      },
      {
        keys: ["new delhi", "delhi"],
        displayCity: "New Delhi",
        displayState: "Delhi",
        country: "India",
        region: "North India",
        latitude: 28.6448,
        longitude: 77.2167,
      },
      {
        keys: ["mumbai"],
        displayCity: "Mumbai",
        displayState: "Maharashtra",
        country: "India",
        region: "West India",
        latitude: 19.076,
        longitude: 72.8777,
      },
      {
        keys: ["bengaluru", "bangalore", "blr"],
        displayCity: "Bengaluru",
        displayState: "Karnataka",
        country: "India",
        region: "South India",
        latitude: 12.9724,
        longitude: 77.5806,
      },
      {
        keys: ["kolkata"],
        displayCity: "Kolkata",
        displayState: "West Bengal",
        country: "India",
        region: "East India",
        latitude: 22.5726,
        longitude: 88.3639,
      },
      {
        keys: ["hyderabad", "hyd"],
        displayCity: "Hyderabad",
        displayState: "Telangana",
        country: "India",
        region: "South India",
        latitude: 17.3871,
        longitude: 78.4917,
      },
      {
        keys: ["visakhapatnam", "bishakhapatnam", "vizag"],
        displayCity: "Visakhapatnam",
        displayState: "Andhra Pradesh",
        country: "India",
        region: "South India",
        latitude: 17.6868,
        longitude: 83.2185,
      },
      {
        keys: ["switzerland", "swiss"],
        displayCity: "Switzerland",
        displayState: "Europe",
        country: "Switzerland",
        region: "Europe",
        latitude: 46.8182,
        longitude: 8.2275,
      },
      {
        keys: ["malaysia", "malasia"],
        displayCity: "Malaysia",
        displayState: "Southeast Asia",
        country: "Malaysia",
        region: "Southeast Asia",
        latitude: 3.139,
        longitude: 101.6869,
      },
      {
        keys: ["indonesia"],
        displayCity: "Indonesia",
        displayState: "Southeast Asia",
        country: "Indonesia",
        region: "Southeast Asia",
        latitude: -6.2,
        longitude: 106.8167,
      },
      {
        keys: ["bhutan"],
        displayCity: "Bhutan",
        displayState: "Himalayan Region",
        country: "Bhutan",
        region: "Himalayan Region",
        latitude: 27.5142,
        longitude: 90.4336,
      },
      {
        keys: ["usa", "united states", "us"],
        displayCity: "USA",
        displayState: "North America",
        country: "United States",
        region: "North America",
        latitude: 37.0902,
        longitude: -95.7129,
      },
      {
        keys: ["uk", "united kingdom", "london"],
        displayCity: "United Kingdom",
        displayState: "Europe",
        country: "United Kingdom",
        region: "Europe",
        latitude: 51.5074,
        longitude: -0.1278,
      },
      {
        keys: ["singapore", "sg"],
        displayCity: "Singapore",
        displayState: "Southeast Asia",
        country: "Singapore",
        region: "Southeast Asia",
        latitude: 1.3521,
        longitude: 103.8198,
      },
    ],
  },
  texts: {
    heading: {
      titlePrefix: "Global Branch ",
      titleHighlight: "Directory",
      description: "Navigate the foundation's connected branch network across India and international regions.",
      findBranch: "Find a branch",
    },
    emptyState: {
      title: "No branch locations found",
      description: (query) => `No locations match "${query}". Try a city, branch ID, region, or country.`,
      clearSearch: "Clear search"
    },
    globe: {
      label: "Global command view",
      title: "Live branch globe",
      highlightedBranch: "Highlighted branch"
    },
    card: {
      selectedBranch: "Selected branch",
      online: "Online",
      branchId: "Branch ID",
      region: "Region",
      primaryContact: "Primary contact",
      role: "Role",
      viewProfile: "View Profile",
      call: "Call",
      email: "Email",
      na: "N/A"
    },
    profile: {
      titlePrefix: "Branch Details",
      officeAddress: "Office address",
      addressNotAvailable: "Address not available",
      branchInfo: "Branch information",
      branchInfoDesc: "Identity and location details for this branch.",
      labels: {
        branchId: "Branch ID",
        serialNo: "Serial number",
        city: "City",
        state: "State",
        country: "Country",
        region: "Region"
      }
    }
  }
};
