export const idCardDetails = {
    slNo: "011",
    idCardPhoto: "https://images.unsplash.com/photo-1580489944761-15a19d654956?fit=crop&w=800&q=80",
    name: "Dr. Kavita Raman",
    firstName: "Kavita",
    middleName: "-",
    lastName: "Raman",
    fatherSName: "S. Raman",
    fatherFirstName: "S.",
    fatherMiddleName: "-",
    fatherLastName: "Raman",
    dateOfBirth: "30-May-1982",
    gender: "Female",
    designation: "Principal Advisory Consultant",
    department: "Cyber Law & Policy Advisory Unit",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Consultant ID",
    employeeStudentMemberId: "CRCCF-CNS-011",
    idCardNumber: "IDC-2024-CNS11",
    issueDate: "10-Jan-2023",
    validFrom: "10-Jan-2023",
    expiryDate: "09-Jan-2026",
    mobileNumber: "+91 9810554433",
    emailId: "kavita.raman@crccf.org",
    address: "78, Barakhamba Road, Connaught Place, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Consultant credential for national legal cyber advisory"
};
