export const certificateDetails = {
    slNo: "037",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Pratiksha Patil",
    certificateHolderFirstName: "Pratiksha",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Patil",
    fatherSName: "Eknath Patil",
    fatherFirstName: "Eknath",
    fatherMiddleName: "-",
    fatherLastName: "Patil",
    dateOfBirth: "25-Jul-1999",
    gender: "Female",
    certificateName: "Technical Skill Development Certificate",
    certificateType: "Skill Development Certification",
    courseQualificationName: "Secure API Development, Cryptographic Implementations & Hardening",
    institutionName: "CRCCF Technical Skill Academy",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-TSD-2024-037",
    certificateNumber: "CERT-TSD-8937",
    issueDate: "20-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director of Skill Development, CRCCF",
    mobileNumber: "+91 9876543137",
    emailId: "pratiksha.patil@example.com",
    address: "CIDCO Colony, Nashik, Maharashtra, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
