export const documentDetails = {
    slNo: "Sample Sl No",
    documentPhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    documentName: "Sample Document Name",
    documentType: "Sample Document Type",
    documentNumber: "Sample Document Number",
    documentCategory: "Sample Document Category",
    documentPurpose: "Sample Document Purpose",
    issuingOrganization: "Sample Issuing Organization",
    issuingAuthority: "Sample Issuing Authority",
    issueDate: "Sample Issue Date",
    validFrom: "Sample Valid From",
    expiryDate: "Sample Expiry Date",
    holderApplicantName: "Sample Holder / Applicant Name",
    fatherSName: "Sample Father's Name",
    dateOfBirth: "Sample Date of Birth",
    address: "Sample Address",
    mobileNumber: "Sample Mobile Number",
    emailId: "Sample Email ID",
    registrationNumber: "Sample Registration Number",
    documentStatus: "Sample Document Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
    remarks: "Sample Remarks",
};