export const idCardDetails = {
    slNo: "020",
    idCardPhoto: "https://images.unsplash.com/photo-1580489944761-15a19d654956?fit=crop&w=800&q=80",
    name: "Dr. Sunita Narain",
    firstName: "Sunita",
    middleName: "-",
    lastName: "Narain",
    fatherSName: "D. C. Narain",
    fatherFirstName: "D.",
    fatherMiddleName: "C.",
    fatherLastName: "Narain",
    dateOfBirth: "14-Dec-1961",
    gender: "Female",
    designation: "Honorary Council Member",
    department: "Council of Honorary Fellows",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Honorary Member ID",
    employeeStudentMemberId: "CRCCF-HNR-020",
    idCardNumber: "IDC-2024-HNR20",
    issueDate: "26-Jan-2022",
    validFrom: "26-Jan-2022",
    expiryDate: "Lifetime",
    mobileNumber: "+91 9811443322",
    emailId: "sunita.narain@honorary.crccf.org",
    address: "Lutyens Zone, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Distinguished public service honorary credential"
};
