export const idCardDetails = {
    slNo: "007",
    idCardPhoto: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?fit=crop&w=800&q=80",
    name: "Sneha Kulkarni",
    firstName: "Sneha",
    middleName: "-",
    lastName: "Kulkarni",
    fatherSName: "Prakash Kulkarni",
    fatherFirstName: "Prakash",
    fatherMiddleName: "-",
    fatherLastName: "Kulkarni",
    dateOfBirth: "29-Nov-1996",
    gender: "Female",
    designation: "Associate Incident Analyst",
    department: "Weekend Incident Response Cell",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Part-Time Employee ID",
    employeeStudentMemberId: "CRCCF-PTE-007",
    idCardNumber: "IDC-2024-PTE07",
    issueDate: "01-Oct-2023",
    validFrom: "01-Oct-2023",
    expiryDate: "30-Sep-2025",
    mobileNumber: "+91 9765432109",
    emailId: "sneha.k@crccf.org",
    address: "12, Shivaji Nagar, Pune, Maharashtra, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Designated shift and technical laboratory clearance"
};
