export const certificateDetails = {
    slNo: "010",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Karthik Iyer",
    certificateHolderFirstName: "Karthik",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Iyer",
    fatherSName: "Venkatesh Iyer",
    fatherFirstName: "Venkatesh",
    fatherMiddleName: "-",
    fatherLastName: "Iyer",
    dateOfBirth: "08-Oct-1996",
    gender: "Male",
    certificateName: "Seminar Certificate",
    certificateType: "Academic Seminar Participation",
    courseQualificationName: "National Seminar on AI-Driven Ransomware Defense",
    institutionName: "Cyber Crime Research Foundation Symposia",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-SC-2024-010",
    certificateNumber: "CERT-SC-8910",
    issueDate: "19-Sep-2024",
    passingYear: "2024",
    gradeMarks: "Delegated Participant",
    certificateValidity: "Permanent Record",
    issuingAuthority: "Seminar Chair, CRCCF",
    mobileNumber: "+91 9876543110",
    emailId: "karthik.iyer@example.com",
    address: "Adyar, Chennai, Tamil Nadu, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
