export const idCardDetails = {
    slNo: "004",
    idCardPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?fit=crop&w=800&q=80",
    name: "Vikramaditya Sen",
    firstName: "Vikramaditya",
    middleName: "-",
    lastName: "Sen",
    fatherSName: "Amitabha Sen",
    fatherFirstName: "Amitabha",
    fatherMiddleName: "-",
    fatherLastName: "Sen",
    dateOfBirth: "05-Sep-1985",
    gender: "Male",
    designation: "General Manager - Operations",
    department: "Central Operations & Administration",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Management ID",
    employeeStudentMemberId: "CRCCF-MGT-004",
    idCardNumber: "IDC-2024-MGT04",
    issueDate: "01-Feb-2023",
    validFrom: "01-Feb-2023",
    expiryDate: "31-Jan-2028",
    mobileNumber: "+91 9820011223",
    emailId: "vikram.sen@crccf.org",
    address: "Apex Corporate Towers, Sector 62, Noida, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Full administrative and procurement sign-off clearance"
};
