export const socialMediaDetails = {
    slNo: "Sample Sl No",
    profilePhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    accountHolderName: "Sample Account Holder Name",
    username: "Sample Username",
    socialMediaPlatform: "Sample Social Media Platform",
    profileUrl: "Sample Profile URL",
    accountId: "Sample Account ID",
    accountType: "Sample Account Type",
    category: "Sample Category",
    organizationName: "Sample Organization Name",
    designation: "Sample Designation",
    registrationDate: "Sample Registration Date",
    followers: "Sample Followers",
    following: "Sample Following",
    verificationMethod: "Sample Verification Method",
    verifiedBadgeStatus: "Sample Verified Badge Status",
    contactEmail: "Sample Contact Email",
    mobileNumber: "Sample Mobile Number",
    website: "Sample Website",
    profileStatus: "Sample Profile Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
    remarks: "Sample Remarks",
};