export const socialMediaDetails = {
    slNo: "001",
    profilePhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    accountHolderName: "Subrajit Sharma",
    accountHolderFirstName: "Subrajit",
    accountHolderMiddleName: "-",
    accountHolderLastName: "Sharma",
    username: "@subrajit_cybersec",
    socialMediaPlatform: "LinkedIn Official Verified",
    profileUrl: "https://linkedin.com/in/subrajit-cybersec",
    accountId: "SOC-2023-8821",
    accountType: "Executive Public Profile",
    category: "Cybersecurity Leadership & Intelligence",
    organizationName: "CR Cyber Crime Foundation",
    designation: "Chief Information Security Officer",
    registrationDate: "14-Mar-2018",
    followers: "12,450+",
    following: "480",
    verificationMethod: "Cryptographic Government ID & Organization Verification",
    verifiedBadgeStatus: "Blue Shield Verified",
    contactEmail: "subrajit@example.com",
    mobileNumber: "+91 9876543210",
    website: "https://crccf.org",
    profileStatus: "Active & Verified",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Digital Identity Cell",
    remarks: "Official verified public profile of organizational leadership",
};