export const certificateDetails = {
    slNo: "025",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Shweta Agarwal",
    certificateHolderFirstName: "Shweta",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Agarwal",
    fatherSName: "Pradeep Agarwal",
    fatherFirstName: "Pradeep",
    fatherMiddleName: "-",
    fatherLastName: "Agarwal",
    dateOfBirth: "04-Jun-2002",
    gender: "Female",
    certificateName: "Cyber Awareness Certificate",
    certificateType: "Public Cyber Safety Credential",
    courseQualificationName: "Cyber Fraud Defense, Phishing Prevention & Digital Safety",
    institutionName: "National Cyber Safety Council",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-CAC-2024-025",
    certificateNumber: "CERT-CAC-8925",
    issueDate: "12-Sep-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director of Cyber Awareness, CRCCF",
    mobileNumber: "+91 9876543125",
    emailId: "shweta.a@example.com",
    address: "Mansarovar, Jaipur, Rajasthan, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
