export const softwareProductDetails = {
    slNo: "Sample Sl No",
    productLogoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    softwareProductName: "Sample Software Product Name",
    productId: "Sample Product ID",
    productType: "Sample Product Type",
    productCategory: "Sample Product Category",
    version: "Sample Version",
    developerName: "Sample Developer Name",
    developerOrganization: "Sample Developer Organization",
    productOwner: "Sample Product Owner",
    softwarePurpose: "Sample Software Purpose",
    keyFeatures: "Sample Key Features",
    platform: "Sample Platform",
    technology: "Sample Technology",
    licenseType: "Sample License Type",
    licenseNumber: "Sample License Number",
    releaseDate: "Sample Release Date",
    currentVersion: "Sample Current Version",
    website: "Sample Website",
    supportEmail: "Sample Support Email",
    supportMobile: "Sample Support Mobile",
    productStatus: "Sample Product Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};