export const idCardDetails = {
    slNo: "030",
    idCardPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?fit=crop&w=800&q=80",
    name: "Alok Khurana",
    firstName: "Alok",
    middleName: "-",
    lastName: "Khurana",
    fatherSName: "K. L. Khurana",
    fatherFirstName: "K.",
    fatherMiddleName: "L.",
    fatherLastName: "Khurana",
    dateOfBirth: "12-Sep-1976",
    gender: "Male",
    designation: "Executive Cyber Mentor",
    department: "Mentorship & Leadership Directorate",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Mentor ID",
    employeeStudentMemberId: "CRCCF-MTR-030",
    idCardNumber: "IDC-2024-MTR30",
    issueDate: "01-Feb-2022",
    validFrom: "01-Feb-2022",
    expiryDate: "31-Jan-2027",
    mobileNumber: "+91 9810112233",
    emailId: "alok.khurana@crccf.org",
    address: "Golf Links, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Senior startup and intelligence mentor for incubation cell"
};
