export const idCardDetails = {
    slNo: "008",
    idCardPhoto: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?fit=crop&w=800&q=80",
    name: "Rohan Deshmukh",
    firstName: "Rohan",
    middleName: "-",
    lastName: "Deshmukh",
    fatherSName: "Sudhir Deshmukh",
    fatherFirstName: "Sudhir",
    fatherMiddleName: "-",
    fatherLastName: "Deshmukh",
    dateOfBirth: "11-Jul-1992",
    gender: "Male",
    designation: "Cloud Forensics Architect",
    department: "National Threat Repository Project",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Project Staff ID",
    employeeStudentMemberId: "CRCCF-PRJ-008",
    idCardNumber: "IDC-2024-PRJ08",
    issueDate: "15-Aug-2023",
    validFrom: "15-Aug-2023",
    expiryDate: "14-Aug-2026",
    mobileNumber: "+91 9822334455",
    emailId: "rohan.d@crccf.org",
    address: "Block 8, Electronic City, Bengaluru, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized for National Threat Portal secure architecture"
};
