export const idCardDetails = {
    slNo: "025",
    idCardPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?fit=crop&w=800&q=80",
    name: "Dr. Pradeep Menon",
    firstName: "Pradeep",
    middleName: "-",
    lastName: "Menon",
    fatherSName: "K. P. Menon",
    fatherFirstName: "K.",
    fatherMiddleName: "P.",
    fatherLastName: "Menon",
    dateOfBirth: "27-Jan-1984",
    gender: "Male",
    designation: "Senior Cyber Threat Researcher",
    department: "Advanced Threat Intelligence Cell",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Researcher ID",
    employeeStudentMemberId: "CRCCF-RES-025",
    idCardNumber: "IDC-2024-RES25",
    issueDate: "01-Jun-2022",
    validFrom: "01-Jun-2022",
    expiryDate: "31-May-2027",
    mobileNumber: "+91 9447113355",
    emailId: "p.menon@crccf.org",
    address: "Infopark, Kakkanad, Kochi, Kerala, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Lead investigator for advanced zero-day threat analysis"
};
