export const idCardDetails = {
    slNo: "034",
    idCardPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?fit=crop&w=800&q=80",
    name: "Kunal Kapoor",
    firstName: "Kunal",
    middleName: "-",
    lastName: "Kapoor",
    fatherSName: "D. P. Kapoor",
    fatherFirstName: "D.",
    fatherMiddleName: "P.",
    fatherLastName: "Kapoor",
    dateOfBirth: "05-Jun-1997",
    gender: "Male",
    designation: "Event Operations Lead",
    department: "National Cyber Conclave Directorate",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Event Staff Credential",
    employeeStudentMemberId: "CRCCF-EVT-034",
    idCardNumber: "IDC-2024-EVT34",
    issueDate: "01-Feb-2024",
    validFrom: "01-Feb-2024",
    expiryDate: "31-Dec-2024",
    mobileNumber: "+91 9818889900",
    emailId: "kunal.k@events.crccf.org",
    address: "Pragati Maidan Conclave Grounds, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "All-access event badge for national delegates and summits"
};
