export const idCardDetails = {
    slNo: "003",
    idCardPhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?fit=crop&w=800&q=80",
    name: "Ananya Verma",
    firstName: "Ananya",
    middleName: "-",
    lastName: "Verma",
    fatherSName: "R. K. Verma",
    fatherFirstName: "R.",
    fatherMiddleName: "K.",
    fatherLastName: "Verma",
    dateOfBirth: "24-Oct-1988",
    gender: "Female",
    designation: "Chief Information Security Officer (CISO)",
    department: "Executive Security Directorate",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Executive Leadership ID",
    employeeStudentMemberId: "CRCCF-EXE-003",
    idCardNumber: "IDC-2024-EXE03",
    issueDate: "10-Jan-2022",
    validFrom: "10-Jan-2022",
    expiryDate: "09-Jan-2027",
    mobileNumber: "+91 9711223344",
    emailId: "ananya.verma@crccf.org",
    address: "Tower B, Executive Enclave, Mumbai, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Tier-1 executive authorization for national security briefings"
};
