export const idCardDetails = {
    slNo: "037",
    idCardPhoto: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?fit=crop&w=800&q=80",
    name: "Vinod Agarwal",
    firstName: "Vinod",
    middleName: "-",
    lastName: "Agarwal",
    fatherSName: "M. P. Agarwal",
    fatherFirstName: "M.",
    fatherMiddleName: "P.",
    fatherLastName: "Agarwal",
    dateOfBirth: "30-Sep-1980",
    gender: "Male",
    designation: "Certified IT Hardware Vendor",
    department: "Systems Procurement & Maintenance Contractor",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Vendor ID",
    employeeStudentMemberId: "CRCCF-VND-037",
    idCardNumber: "IDC-2024-VND37",
    issueDate: "01-Jan-2024",
    validFrom: "01-Jan-2024",
    expiryDate: "31-Dec-2025",
    mobileNumber: "+91 9811440011",
    emailId: "vinod.agarwal@vendors.crccf.org",
    address: "Nehru Place IT Hub, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized for server rack servicing and IT asset maintenance"
};
