export const idCardDetails = {
    slNo: "022",
    idCardPhoto: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?fit=crop&w=800&q=80",
    name: "Ishaan Kapoor",
    firstName: "Ishaan",
    middleName: "-",
    lastName: "Kapoor",
    fatherSName: "Rakesh Kapoor",
    fatherFirstName: "Rakesh",
    fatherMiddleName: "-",
    fatherLastName: "Kapoor",
    dateOfBirth: "04-Apr-2002",
    gender: "Male",
    designation: "Cyber Forensics Intern",
    department: "Forensic Evidence Lab Training Cell",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Student Intern ID",
    employeeStudentMemberId: "CRCCF-INT-022",
    idCardNumber: "IDC-2024-INT22",
    issueDate: "01-Jan-2024",
    validFrom: "01-Jan-2024",
    expiryDate: "30-Jun-2024",
    mobileNumber: "+91 9899001122",
    emailId: "ishaan.k@interns.crccf.org",
    address: "Hostel Block 3, IIT Roorkee, Uttarakhand, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized for lab workstations during supervised internship"
};
