export const certificateDetails = {
    slNo: "014",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Dr. Alok Bhargava",
    certificateHolderFirstName: "Alok",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Bhargava",
    fatherSName: "S. P. Bhargava",
    fatherFirstName: "S.",
    fatherMiddleName: "P.",
    fatherLastName: "Bhargava",
    dateOfBirth: "17-May-1979",
    gender: "Male",
    certificateName: "Membership Certificate",
    certificateType: "Professional Fellow Membership",
    courseQualificationName: "Senior Fellow in Cyber Intelligence & Threat Research",
    institutionName: "Cyber Crime Research & Crime Foundation",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-MC-2024-014",
    certificateNumber: "CERT-MC-8914",
    issueDate: "01-Jan-2024",
    passingYear: "2024",
    gradeMarks: "Fellow (F-CRCCF)",
    certificateValidity: "Annual Renewal / Active",
    issuingAuthority: "Secretary General, CRCCF",
    mobileNumber: "+91 9876543114",
    emailId: "dr.alok@example.com",
    address: "Aliganj, Lucknow, Uttar Pradesh, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
