export const certificateDetails = {
    slNo: "028",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Neha Singhania",
    certificateHolderFirstName: "Neha",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Singhania",
    fatherSName: "Anil Singhania",
    fatherFirstName: "Anil",
    fatherMiddleName: "-",
    fatherLastName: "Singhania",
    dateOfBirth: "30-Jan-1996",
    gender: "Female",
    certificateName: "Digital Forensics Certificate",
    certificateType: "Certified Forensic Specialist",
    courseQualificationName: "Disk, Memory & Mobile Device Forensic Analysis",
    institutionName: "Digital Forensics & Evidence Laboratory",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-DFC-2024-028",
    certificateNumber: "CERT-DFC-8928",
    issueDate: "20-Aug-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Chief Forensic Examiner, CRCCF",
    mobileNumber: "+91 9876543128",
    emailId: "neha.singhania@example.com",
    address: "Civil Lines, Kanpur, Uttar Pradesh, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
