export const certificateDetails = {
    slNo: "006",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Adv. Siddharth Deshmukh",
    certificateHolderFirstName: "Siddharth",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Deshmukh",
    fatherSName: "Vasant Deshmukh",
    fatherFirstName: "Vasant",
    fatherMiddleName: "-",
    fatherLastName: "Deshmukh",
    dateOfBirth: "11-May-1991",
    gender: "Male",
    certificateName: "Legal Education Certificate",
    certificateType: "Continuing Legal Education",
    courseQualificationName: "Cyber Crime Law, IT Act 2000 & Digital Evidence Practice",
    institutionName: "National Cyber Jurisprudence Academy",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-LEC-2024-006",
    certificateNumber: "CERT-LEC-8906",
    issueDate: "12-Jul-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director of Legal Affairs, CRCCF",
    mobileNumber: "+91 9876543106",
    emailId: "siddharth.law@example.com",
    address: "Nariman Point, Mumbai, Maharashtra, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
