export const materialDetails = {
    slNo: "Sample Sl No",
    materialName: "Sample Material Name",
    materialId: "Sample Material ID",
    materialType: "Sample Material Type",

    materialTitle: "Sample Material Title",
    materialRegistrationId: "Sample Material Registration ID",
    materialPublisher: "Sample Material Publisher",
    authorFirstName: "Vikram",
    authorMiddleName: "Kumar",
    authorLastName: "Singhania",
    author: "Vikram Kumar Singhania",
    materialPublishedDate: "Sample Material Published Date",
    noOfPages: "Sample No Of Pages",
    modules: "Sample Modules",
    noOfChapters: "Sample No Of Chapters",
    paragraph: "Sample Paragraph",
    noOfCharacters: "Sample No Of Characters",

    materialCategory: "Sample Material Category",
    materialDescription: "Sample Material Description",
    manufacturerFirstName: "Rajesh",
    manufacturerMiddleName: "Kumar",
    manufacturerLastName: "Gupta",
    manufacturerName: "Rajesh Kumar Gupta",
    manufacturerOrganization: "Sample Manufacturer Organization",
    supplierFirstName: "Anil",
    supplierMiddleName: "Kumar",
    supplierLastName: "Mehta",
    supplierName: "Anil Kumar Mehta",
    supplierOrganization: "Sample Supplier Organization",
    batchNumber: "Sample Batch Number",
    serialNumber: "Sample Serial Number",
    manufacturingDate: "Sample Manufacturing Date",
    contactNumber: "Sample Contact Number",
    emailId: "Sample Email ID",
    materialStatus: "Sample Material Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};