export const materialDetails = {
    slNo: "Sample Sl No",
    materialName: "Sample Material Name",
    materialId: "Sample Material ID",
    materialType: "Sample Material Type",

    materialTitle: "Sample Material Title",
    materialRegistrationId: "Sample Material Registration ID",
    materialPublisher: "Sample Material Publisher",
    author: "Sample Author",
    materialPublishedDate: "Sample Material Published Date",
    noOfPages: "Sample No Of Pages",
    modules: "Sample Modules",
    noOfChapters: "Sample No Of Chapters",
    paragraph: "Sample Paragraph",
    noOfCharacters: "Sample No Of Characters",

    materialCategory: "Sample Material Category",
    materialDescription: "Sample Material Description",
    manufacturerName: "Sample Manufacturer Name",
    manufacturerOrganization: "Sample Manufacturer Organization",
    supplierName: "Sample Supplier Name",
    supplierOrganization: "Sample Supplier Organization",
    batchNumber: "Sample Batch Number",
    serialNumber: "Sample Serial Number",
    manufacturingDate: "Sample Manufacturing Date",
    contactNumber: "Sample Contact Number",
    emailId: "Sample Email ID",
    materialStatus: "Sample Material Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};