export const materialDetails = {
    slNo: "Sample Sl No",
    materialPhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    materialName: "Sample Material Name",
    materialId: "Sample Material ID",
    materialType: "Sample Material Type",
    materialCategory: "Sample Material Category",
    materialDescription: "Sample Material Description",
    manufacturerName: "Sample Manufacturer Name",
    manufacturerOrganization: "Sample Manufacturer Organization",
    supplierName: "Sample Supplier Name",
    supplierOrganization: "Sample Supplier Organization",
    batchNumber: "Sample Batch Number",
    serialNumber: "Sample Serial Number",
    manufacturingDate: "Sample Manufacturing Date",
    expiryDate: "Sample Expiry Date",
    quantity: "Sample Quantity",
    unit: "Sample Unit",
    qualityGrade: "Sample Quality / Grade",
    certificationNumber: "Sample Certification Number",
    registrationNumber: "Sample Registration Number",
    contactNumber: "Sample Contact Number",
    emailId: "Sample Email ID",
    materialStatus: "Sample Material Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};