export const invitationDetails = {
    slNo: "001",
    invitationPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    invitationNumber: "INV-2023-9901",
    invitationTitle: "National Cyber Security Summit 2023",
    invitationType: "VIP Delegate Invitation",
    hostName: "Dr. Sanjay Kumar",
    hostFirstName: "Dr. Sanjay",
    hostMiddleName: "-",
    hostLastName: "Kumar",
    hostOrganization: "CR Cyber Crime Foundation",
    hostDepartment: "Executive Advisory Council",
    inviteeName: "Subrajit Sharma",
    inviteeFirstName: "Subrajit",
    inviteeMiddleName: "-",
    inviteeLastName: "Sharma",
    inviteeOrganization: "Tech Security Research Labs",
    eventName: "Annual Cyber Defense & Intelligence Conclave",
    eventType: "Keynote & Panel Discussion",
    eventDate: "25-Nov-2023",
    eventTime: "10:00 AM - 05:00 PM",
    venue: "Main Auditorium, Technology Bhavan, Bhubaneswar",
    eventPurpose: "Strategic Deliberation on AI in Cyber Defense",
    numberOfPersons: "2",
    authorizedPersonName: "Rakesh Verma",
    authorizedPersonFirstName: "Rakesh",
    authorizedPersonMiddleName: "-",
    authorizedPersonLastName: "Verma",
    mobileNumber: "+91 9876543210",
    emailId: "subrajit@example.com",
    registrationNumber: "INV-009",
    invitationStatus: "Confirmed & Verified",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Protocol & Events Desk",
};