export const invitationDetails = {
    slNo: "Sample Sl No",
    invitationPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    invitationNumber: "Sample Invitation Number",
    invitationTitle: "Sample Invitation Title",
    invitationType: "Sample Invitation Type",
    hostName: "Sample Host Name",
    hostOrganization: "Sample Host Organization",
    hostDepartment: "Sample Host Department",
    inviteeName: "Sample Invitee Name",
    inviteeOrganization: "Sample Invitee Organization",
    eventName: "Sample Event Name",
    eventType: "Sample Event Type",
    eventDate: "Sample Event Date",
    eventTime: "Sample Event Time",
    venue: "Sample Venue",
    eventPurpose: "Sample Event Purpose",
    numberOfPersons: "Sample Number of Persons",
    authorizedPersonName: "Sample Authorized Person Name",
    mobileNumber: "Sample Mobile Number",
    emailId: "Sample Email ID",
    registrationNumber: "Sample Registration Number",
    invitationStatus: "Sample Invitation Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};