export const idCardDetails = {
    slNo: "027",
    idCardPhoto: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?fit=crop&w=800&q=80",
    name: "Sandeep Roy",
    firstName: "Sandeep",
    middleName: "-",
    lastName: "Roy",
    fatherSName: "Nirmal Roy",
    fatherFirstName: "Nirmal",
    fatherMiddleName: "-",
    fatherLastName: "Roy",
    dateOfBirth: "18-Oct-1987",
    gender: "Male",
    designation: "Lead Certified Cyber Trainer",
    department: "Law Enforcement Capacity Building Academy",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Master Trainer ID",
    employeeStudentMemberId: "CRCCF-TRN-027",
    idCardNumber: "IDC-2024-TRN27",
    issueDate: "10-Feb-2023",
    validFrom: "10-Feb-2023",
    expiryDate: "09-Feb-2028",
    mobileNumber: "+91 9830554433",
    emailId: "sandeep.roy@crccf.org",
    address: "Police Academy Road, Hyderabad, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Certified trainer for state and central cyber crime wings"
};
