export const certificateDetails = {
    slNo: "005",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Kavita Nair",
    certificateHolderFirstName: "Kavita",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Nair",
    fatherSName: "Madhavan Nair",
    fatherFirstName: "Madhavan",
    fatherMiddleName: "-",
    fatherLastName: "Nair",
    dateOfBirth: "14-Jan-1994",
    gender: "Female",
    certificateName: "Experience Certificate",
    certificateType: "Professional Service Credential",
    courseQualificationName: "3 Years Professional Tenure as Senior SOC Analyst",
    institutionName: "CRCCF Cyber Security Operations Center",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-EXP-2024-005",
    certificateNumber: "CERT-EXP-8905",
    issueDate: "30-Sep-2024",
    passingYear: "2024",
    gradeMarks: "Exemplary Performance",
    certificateValidity: "Permanent Record",
    issuingAuthority: "Head of Human Resources, CRCCF",
    mobileNumber: "+91 9876543105",
    emailId: "kavita.nair@example.com",
    address: "Indiranagar, Bengaluru, Karnataka, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
