export const idCardDetails = {
    slNo: "006",
    idCardPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?fit=crop&w=800&q=80",
    name: "Manish Malhotra",
    firstName: "Manish",
    middleName: "-",
    lastName: "Malhotra",
    fatherSName: "Satish Malhotra",
    fatherFirstName: "Satish",
    fatherMiddleName: "-",
    fatherLastName: "Malhotra",
    dateOfBirth: "14-Feb-1994",
    gender: "Male",
    designation: "Contract Security Specialist",
    department: "Infrastructure Security Operations",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Contract Employee ID",
    employeeStudentMemberId: "CRCCF-CNT-006",
    idCardNumber: "IDC-2024-CNT06",
    issueDate: "01-Jul-2023",
    validFrom: "01-Jul-2023",
    expiryDate: "30-Jun-2025",
    mobileNumber: "+91 9811998877",
    emailId: "manish.m@crccf.org",
    address: "74, Cyber City, Phase 3, Gurugram, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Valid for designated contractual assignment period"
};
