export const organizationDetails = {
    slNo: "001",
    organizationLogo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    organizationName: "CR Cyber Crime Foundation",
    organizationRegistrationNumber: "ORG-2021-9920",
    organizationType: "Section 8 Non-Profit Technology Entity",
    organizationCategory: "Information Technology & Cyber Security",
    organizationActivity: "Cyber Threat Intelligence & Public Safety Research",
    organizationStatus: "Active & Accredited",
    registrationDate: "15-Aug-2021",
    incorporationDate: "15-Aug-2021",
    cinRegistrationId: "U72900OR2021NPL038910",
    panNumber: "AAATC1234F",
    gstNumber: "21AAATC1234F1Z5",
    issuingRegistrationAuthority: "Registrar of Companies (RoC), Odisha",
    authorizedPersonName: "Subrajit Sharma",
    authorizedPersonFirstName: "Subrajit",
    authorizedPersonMiddleName: "-",
    authorizedPersonLastName: "Sharma",
    authorizedPersonDesignation: "Director & Chief Operating Officer",
    organizationAddress: "Plot 108, Cyber City Phase 2, Patia",
    city: "Bhubaneswar",
    state: "Odisha",
    country: "India",
    pinCode: "751024",
    mobileNumber: "+91 9876543210",
    emailId: "contact@crccf.org",
    website: "https://crccf.org",
    organizationServices: "Cyber Crime Forensics, Fraud Verification, Threat Intelligence",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Corporate Verification Cell",
    remarks: "Fully compliant with all statutory and legal mandates",
};