export const organizationDetails = {
    slNo: "Sample Sl No",
    organizationLogo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    organizationName: "Sample Organization Name",
    organizationRegistrationNumber: "Sample Organization Registration Number",
    organizationType: "Sample Organization Type",
    organizationCategory: "Sample Organization Category",
    organizationActivity: "Sample Organization Activity",
    organizationStatus: "Sample Organization Status",
    registrationDate: "Sample Registration Date",
    incorporationDate: "Sample Incorporation Date",
    cinRegistrationId: "Sample CIN / Registration ID",
    panNumber: "Sample PAN Number",
    gstNumber: "Sample GST Number",
    issuingRegistrationAuthority: "Sample Issuing / Registration Authority",
    authorizedPersonName: "Sample Authorized Person Name",
    authorizedPersonDesignation: "Sample Authorized Person Designation",
    organizationAddress: "Sample Organization Address",
    city: "Sample City",
    state: "Sample State",
    country: "Sample Country",
    pinCode: "Sample PIN Code",
    mobileNumber: "Sample Mobile Number",
    emailId: "Sample Email ID",
    website: "Sample Website",
    organizationServices: "Sample Organization Services",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
    remarks: "Sample Remarks",
};