export const idCardDetails = {
    slNo: "002",
    idCardPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?fit=crop&w=800&q=80",
    name: "Rajesh Nair",
    firstName: "Rajesh",
    middleName: "-",
    lastName: "Nair",
    fatherSName: "K. R. Nair",
    fatherFirstName: "K.",
    fatherMiddleName: "R.",
    fatherLastName: "Nair",
    dateOfBirth: "12-Apr-1990",
    gender: "Male",
    designation: "Cyber Investigation Officer",
    department: "Special Cyber Crime Investigation Unit",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Investigation Officer ID",
    employeeStudentMemberId: "CRCCF-OFF-002",
    idCardNumber: "IDC-2024-OFF02",
    issueDate: "15-Mar-2023",
    validFrom: "15-Mar-2023",
    expiryDate: "14-Mar-2028",
    mobileNumber: "+91 9845123456",
    emailId: "rajesh.nair@crccf.org",
    address: "Plot 45, Cyber Crime Cell Complex, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized for judicial forensic evidence handling and cyber audits"
};
