export const authorizationDetails = {
    slNo: "Sample Sl No",
    authorizationDocumentPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    authorizationNumber: "Sample Authorization Number",
    authorizationTitle: "Sample Authorization Title",
    authorizedPersonName: "Sample Authorized Person Name",
    fatherSName: "Sample Father's Name",
    dateOfBirth: "Sample Date of Birth",
    gender: "Sample Gender",
    designation: "Sample Designation",
    department: "Sample Department",
    organization: "Sample Organization",
    authorizationType: "Sample Authorization Type",
    authorizationPurpose: "Sample Authorization Purpose",
    authorizedActivity: "Sample Authorized Activity",
    authorityGranted: "Sample Authority Granted",
    issuingAuthority: "Sample Issuing Authority",
    issueDate: "Sample Issue Date",
    validFrom: "Sample Valid From",
    expiryDate: "Sample Expiry Date",
    authorizedSignatory: "Sample Authorized Signatory",
    mobileNumber: "Sample Mobile Number",
    emailId: "Sample Email ID",
    address: "Sample Address",
    authorizationStatus: "Sample Authorization Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};