export const authorizationDetails = {
    slNo: "001",
    authorizationDocumentPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    authorizationNumber: "AUTH-2023-8812",
    authorizationTitle: "Official Digital Forensics & Investigation Authorization",
    authorizedPersonName: "Subrajit Sharma",
    authorizedPersonFirstName: "Subrajit",
    authorizedPersonMiddleName: "-",
    authorizedPersonLastName: "Sharma",
    fatherSName: "Sanjay Kumar",
    fatherFirstName: "Sanjay",
    fatherMiddleName: "-",
    fatherLastName: "Kumar",
    dateOfBirth: "15-Aug-1995",
    gender: "Male",
    designation: "Senior Cyber Crime Forensic Investigator",
    department: "Special Cyber Crime Investigation Cell",
    organization: "CR Cyber Crime Foundation",
    authorizationType: "Statutory Law Enforcement Assistance",
    authorizationPurpose: "Cyber Forensic Evidence Gathering & Infrastructure Inspection",
    authorizedActivity: "High-Priority Cyber Threat & Fraud Investigation",
    authorityGranted: "Forensic Imaging, Incident Triage & Evidence Submission",
    issuingAuthority: "Director General, CRCCF Central Command",
    issueDate: "10-Oct-2023",
    validFrom: "10-Oct-2023",
    expiryDate: "09-Oct-2026",
    authorizedSignatory: "Ramesh Sharma",
    authorizedSignatoryFirstName: "Ramesh",
    authorizedSignatoryMiddleName: "-",
    authorizedSignatoryLastName: "Sharma",
    mobileNumber: "+91 9876543210",
    emailId: "subrajit@example.com",
    address: "123, Tech Park Avenue, Block C, Bhubaneswar, India",
    authorizationStatus: "Authorized & Active",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Regulatory & Statutory Council",
};