export const idCardDetails = {
    slNo: "009",
    idCardPhoto: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?fit=crop&w=800&q=80",
    name: "Tanya Batra",
    firstName: "Tanya",
    middleName: "-",
    lastName: "Batra",
    fatherSName: "Sunil Batra",
    fatherFirstName: "Sunil",
    fatherMiddleName: "-",
    fatherLastName: "Batra",
    dateOfBirth: "08-Dec-1998",
    gender: "Female",
    designation: "Probationary Cyber Analyst",
    department: "SOC Threat Monitoring Lab",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Probationary Employee ID",
    employeeStudentMemberId: "CRCCF-PRB-009",
    idCardNumber: "IDC-2024-PRB09",
    issueDate: "01-Jan-2024",
    validFrom: "01-Jan-2024",
    expiryDate: "31-Dec-2024",
    mobileNumber: "+91 9871122446",
    emailId: "tanya.batra@crccf.org",
    address: "45, Model Town, Chandigarh, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Probation status under review for permanent induction"
};
