export const certificateDetails = {
    slNo: "009",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Pooja Sen",
    certificateHolderFirstName: "Pooja",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Sen",
    fatherSName: "Pranab Sen",
    fatherFirstName: "Pranab",
    fatherMiddleName: "-",
    fatherLastName: "Sen",
    dateOfBirth: "19-Dec-2002",
    gender: "Female",
    certificateName: "General Education Certificate",
    certificateType: "Foundational Cyber Literacy",
    courseQualificationName: "Essential Cyber Hygiene & Digital Safety Fundamentals",
    institutionName: "CRCCF Cyber Literacy Mission",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-GEC-2024-009",
    certificateNumber: "CERT-GEC-8909",
    issueDate: "25-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Grade A",
    certificateValidity: "Lifetime",
    issuingAuthority: "Director of Public Literacy, CRCCF",
    mobileNumber: "+91 9876543109",
    emailId: "pooja.sen@example.com",
    address: "Ballygunge, Kolkata, West Bengal, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
