export const idCardDetails = {
    slNo: "018",
    idCardPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    name: "Dr. Naresh Goyal",
    firstName: "Naresh",
    middleName: "-",
    lastName: "Goyal",
    fatherSName: "H. L. Goyal",
    fatherFirstName: "H.",
    fatherMiddleName: "L.",
    fatherLastName: "Goyal",
    dateOfBirth: "10-Oct-1965",
    gender: "Male",
    designation: "Distinguished Life Member",
    department: "Fellowship & Honors Directorate",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Permanent Life Member ID",
    employeeStudentMemberId: "CRCCF-LFM-018",
    idCardNumber: "IDC-2024-LFM18",
    issueDate: "15-Aug-2020",
    validFrom: "15-Aug-2020",
    expiryDate: "Lifetime",
    mobileNumber: "+91 9811229900",
    emailId: "dr.goyal@lifemembers.crccf.org",
    address: "Civil Lines, Jaipur, Rajasthan, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Lifetime honorary member with perpetual privileges"
};
