export const idCardDetails = {
    slNo: "031",
    idCardPhoto: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?fit=crop&w=800&q=80",
    name: "Neha Choudhury",
    firstName: "Neha",
    middleName: "-",
    lastName: "Choudhury",
    fatherSName: "Debashis Choudhury",
    fatherFirstName: "Debashis",
    fatherMiddleName: "-",
    fatherLastName: "Choudhury",
    dateOfBirth: "03-Mar-2001",
    gender: "Female",
    designation: "Cyber Safety Community Volunteer",
    department: "National Cyber Awareness Outreach Cell",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Volunteer ID",
    employeeStudentMemberId: "CRCCF-VOL-031",
    idCardNumber: "IDC-2024-VOL31",
    issueDate: "01-Jan-2024",
    validFrom: "01-Jan-2024",
    expiryDate: "31-Dec-2025",
    mobileNumber: "+91 9861223344",
    emailId: "neha.c@volunteers.crccf.org",
    address: "Khandagiri, Bhubaneswar, Odisha, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Accredited volunteer for school cyber safety awareness programs"
};
