export const idCardDetails = {
    slNo: "029",
    idCardPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    name: "Dr. Rohit Banerjee",
    firstName: "Rohit",
    middleName: "-",
    lastName: "Banerjee",
    fatherSName: "Samir Banerjee",
    fatherFirstName: "Samir",
    fatherMiddleName: "-",
    fatherLastName: "Banerjee",
    dateOfBirth: "25-Aug-1986",
    gender: "Male",
    designation: "Senior Cyber Warfare Fellow",
    department: "National Strategic Defense Fellowship",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Fellowship Scholar ID",
    employeeStudentMemberId: "CRCCF-FEL-029",
    idCardNumber: "IDC-2024-FEL29",
    issueDate: "01-Apr-2023",
    validFrom: "01-Apr-2023",
    expiryDate: "31-Mar-2026",
    mobileNumber: "+91 9831998800",
    emailId: "rohit.banerjee@fellows.crccf.org",
    address: "Park Street, Kolkata, West Bengal, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Postdoctoral fellow on critical national cyber infrastructure"
};
