export const certificateDetails = {
    slNo: "033",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Kunal Grover",
    certificateHolderFirstName: "Kunal",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Grover",
    fatherSName: "Anand Grover",
    fatherFirstName: "Anand",
    fatherMiddleName: "-",
    fatherLastName: "Grover",
    dateOfBirth: "21-Aug-1997",
    gender: "Male",
    certificateName: "Ethical Hacking Certificate",
    certificateType: "Offensive Security Credential",
    courseQualificationName: "Certified Penetration Tester & Bug Bounty Specialist",
    institutionName: "Offensive Cyber Warfare & Defense Lab",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-EHC-2024-033",
    certificateNumber: "CERT-EHC-8933",
    issueDate: "05-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Head of Offensive Security, CRCCF",
    mobileNumber: "+91 9876543133",
    emailId: "kunal.grover@example.com",
    address: "Sector 29, Gurgaon, Haryana, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
