export const idCardDetails = {
    slNo: "Sample Sl No",
    idCardPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    name: "Sample Name",
    fatherSName: "Sample Father's Name",
    dateOfBirth: "Sample Date of Birth",
    gender: "Sample Gender",
    designation: "Sample Designation",
    department: "Sample Department",
    organizationName: "Sample Organization Name",
    idCardType: "Sample ID Card Type",
    employeeStudentMemberId: "Sample Employee / Student / Member ID",
    idCardNumber: "Sample ID Card Number",
    issueDate: "Sample Issue Date",
    validFrom: "Sample Valid From",
    expiryDate: "Sample Expiry Date",
    mobileNumber: "Sample Mobile Number",
    emailId: "Sample Email ID",
    address: "Sample Address",
    issuedBy: "Sample Issued By",
    approvedBy: "Sample Approved By",
    idCardStatus: "Sample ID Card Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
    remarks: "Sample Remarks",
};