export const idCardDetails = {
    slNo: "001",
    idCardPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    name: "Subrajit Sharma",
    firstName: "Subrajit",
    middleName: "-",
    lastName: "Sharma",
    fatherSName: "Sanjay Kumar",
    fatherFirstName: "Sanjay",
    fatherMiddleName: "-",
    fatherLastName: "Kumar",
    dateOfBirth: "15-Aug-1995",
    gender: "Male",
    designation: "Lead Cybersecurity Officer",
    department: "Digital Forensics & Incident Response",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Permanent Employee ID",
    employeeStudentMemberId: "CRCCF-EMP-009",
    idCardNumber: "IDC-2023-9921",
    issueDate: "01-Jan-2023",
    validFrom: "01-Jan-2023",
    expiryDate: "31-Dec-2028",
    mobileNumber: "+91 9876543210",
    emailId: "subrajit@example.com",
    address: "123, Tech Park Avenue, Block C, Bhubaneswar, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Authorized for official high-security perimeter access",
};