export const certificateDetails = {
    slNo: "004",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Vikram Aditya",
    certificateHolderFirstName: "Vikram",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Aditya",
    fatherSName: "Raghavendra Rao",
    fatherFirstName: "Raghavendra",
    fatherMiddleName: "-",
    fatherLastName: "Rao",
    dateOfBirth: "05-Apr-1996",
    gender: "Male",
    certificateName: "Education Certificate",
    certificateType: "Postgraduate Academic Credential",
    courseQualificationName: "Postgraduate Diploma in Digital Forensics",
    institutionName: "Cyber Law & Digital Defense University",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-EC-2024-004",
    certificateNumber: "CERT-EC-8904",
    issueDate: "20-Jun-2024",
    passingYear: "2024",
    gradeMarks: "First Class with Distinction",
    certificateValidity: "Lifetime",
    issuingAuthority: "Registrar, Academic Affairs, CRCCF",
    mobileNumber: "+91 9876543104",
    emailId: "vikram.aditya@example.com",
    address: "Banjara Hills, Hyderabad, Telangana, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
