export const certificateDetails = {
    slNo: "020",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Saurabh Ganguly",
    certificateHolderFirstName: "Saurabh",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Ganguly",
    fatherSName: "Somenath Ganguly",
    fatherFirstName: "Somenath",
    fatherMiddleName: "-",
    fatherLastName: "Ganguly",
    dateOfBirth: "08-Jan-1999",
    gender: "Male",
    certificateName: "Best Performer Certificate",
    certificateType: "Hackathon & Drill Champion",
    courseQualificationName: "National Blue Team Cyber Drill Champion 2024",
    institutionName: "CRCCF Skill Competitions Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-BPC-2024-020",
    certificateNumber: "CERT-BPC-8920",
    issueDate: "10-Nov-2024",
    passingYear: "2024",
    gradeMarks: "First Rank Overall",
    certificateValidity: "Permanent Honor",
    issuingAuthority: "Director of Skill Development, CRCCF",
    mobileNumber: "+91 9876543120",
    emailId: "saurabh.g@example.com",
    address: "Gariahat, Kolkata, West Bengal, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
