export const certificateDetails = {
    slNo: "024",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Varun Choudhury",
    certificateHolderFirstName: "Varun",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Choudhury",
    fatherSName: "B. K. Choudhury",
    fatherFirstName: "B.",
    fatherMiddleName: "K.",
    fatherLastName: "Choudhury",
    dateOfBirth: "20-Oct-1998",
    gender: "Male",
    certificateName: "Project Completion Certificate",
    certificateType: "Technical Project Deliverable",
    courseQualificationName: "Autonomous Threat Analysis & SIEM Integration System",
    institutionName: "CRCCF Project Management Office",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-PCC-2024-024",
    certificateNumber: "CERT-PCC-8924",
    issueDate: "28-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Completed with Distinction",
    certificateValidity: "Lifetime",
    issuingAuthority: "Project Director, CRCCF",
    mobileNumber: "+91 9876543124",
    emailId: "varun.choudhury@example.com",
    address: "Boring Road, Patna, Bihar, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
