export const certificateDetails = {
    slNo: "040",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Tarun Venkatesh",
    certificateHolderFirstName: "Tarun",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Venkatesh",
    fatherSName: "S. Venkatesh",
    fatherFirstName: "S.",
    fatherMiddleName: "-",
    fatherLastName: "Venkatesh",
    dateOfBirth: "28-Jun-1993",
    gender: "Male",
    certificateName: "Cyber Risk Management Certificate",
    certificateType: "Enterprise Risk Credential",
    courseQualificationName: "Enterprise Cyber Threat Risk Quantification (FAIR Framework)",
    institutionName: "CRCCF Enterprise Risk Governance Institute",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-CRM-2024-040",
    certificateNumber: "CERT-CRM-8940",
    issueDate: "18-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Head of Risk & Governance, CRCCF",
    mobileNumber: "+91 9876543140",
    emailId: "tarun.venkatesh@example.com",
    address: "Alwarpet, Chennai, Tamil Nadu, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
