export const idCardDetails = {
    slNo: "032",
    idCardPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?fit=crop&w=800&q=80",
    name: "Inspector Balraj Singh",
    firstName: "Balraj",
    middleName: "-",
    lastName: "Singh",
    fatherSName: "Harbans Singh",
    fatherFirstName: "Harbans",
    fatherMiddleName: "-",
    fatherLastName: "Singh",
    dateOfBirth: "15-Aug-1983",
    gender: "Male",
    designation: "Field Intelligence Officer",
    department: "Rapid Cyber Crime Action Force",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Field Officer Special ID",
    employeeStudentMemberId: "CRCCF-FLD-032",
    idCardNumber: "IDC-2024-FLD32",
    issueDate: "01-Jan-2023",
    validFrom: "01-Jan-2023",
    expiryDate: "31-Dec-2027",
    mobileNumber: "+91 9814112233",
    emailId: "balraj.singh@crccf.org",
    address: "Police Lines, Sector 26, Chandigarh, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Armed tactical cyber forensics field response authorization"
};
