export const certificateDetails = {
    slNo: "002",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Rohan Kulkarni",
    certificateHolderFirstName: "Rohan",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Kulkarni",
    fatherSName: "Mahesh Kulkarni",
    fatherFirstName: "Mahesh",
    fatherMiddleName: "-",
    fatherLastName: "Kulkarni",
    dateOfBirth: "18-Sep-1998",
    gender: "Male",
    certificateName: "Training Certificate",
    certificateType: "Advanced Professional Training",
    courseQualificationName: "Hands-on Network Defense & Threat Hunting",
    institutionName: "National Cyber Defense Training Academy",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-TC-2024-002",
    certificateNumber: "CERT-TC-8902",
    issueDate: "10-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Grade A (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Chief Training Officer, CRCCF",
    mobileNumber: "+91 9876543102",
    emailId: "rohan.kulkarni@example.com",
    address: "Shivaji Nagar, Pune, Maharashtra, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
