export const visitorDetails = {
    visitorPersonName: "Subrajit",
    age: "28",
    gender: "Male",
    address: "123, Tech Park Avenue, Block C, Bhubaneswar, India",
    occupation: "Software Engineer",
    department: "IT",
    visitDate: "15-Sep-2023",
    timing: "10:00 AM",
    visitPurpose: "Business Meeting",
    personToMeet: "Rakesh Sharma",
    personToMeetDepartment: "HR Department",
    entryTime: "09:55 AM",
    exitTime: "11:30 AM",
    totalDuration: "1 Hour 35 Minutes",
    numberOfPersonsVisit: "1",
    vehicleNo: "OD-02-AB-1234",
    vehicleType: "Two Wheeler",
    appointmentAuthorisePersonNameAndDepartment: "Suresh Kumar (Admin)",
    mobileNumber: "+91 9876543210",
    mailId: "subrajit@example.com",
    registrationNumber: "009",
    status: "Approved"
};
