export const idCardDetails = {
    slNo: "013",
    idCardPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    name: "Prof. Harish Chandra",
    firstName: "Harish",
    middleName: "-",
    lastName: "Chandra",
    fatherSName: "N. C. Chandra",
    fatherFirstName: "N.",
    fatherMiddleName: "C.",
    fatherLastName: "Chandra",
    dateOfBirth: "02-Aug-1968",
    gender: "Male",
    designation: "Senior Advisory Council Member",
    department: "National Strategic Advisory Board",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Advisory Board ID",
    employeeStudentMemberId: "CRCCF-ADV-013",
    idCardNumber: "IDC-2024-ADV13",
    issueDate: "01-Jan-2022",
    validFrom: "01-Jan-2022",
    expiryDate: "31-Dec-2027",
    mobileNumber: "+91 9818002233",
    emailId: "advisory.chandra@crccf.org",
    address: "IIT Delhi Campus, Hauz Khas, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Honorary strategic advisor for national cyber resilience"
};
