export const certificateDetails = {
    slNo: "019",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Ritu Chawla",
    certificateHolderFirstName: "Ritu",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Chawla",
    fatherSName: "Davinder Chawla",
    fatherFirstName: "Davinder",
    fatherMiddleName: "-",
    fatherLastName: "Chawla",
    dateOfBirth: "19-Apr-1997",
    gender: "Female",
    certificateName: "Outstanding Performance Certificate",
    certificateType: "Operational Performance Citation",
    courseQualificationName: "Exemplary Threat Hunting & Zero-Downtime Defense Operations",
    institutionName: "CRCCF Cyber Operations Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-OPC-2024-019",
    certificateNumber: "CERT-OPC-8919",
    issueDate: "15-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Exceeds Expectations (Grade O)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Chief Operations Officer, CRCCF",
    mobileNumber: "+91 9876543119",
    emailId: "ritu.chawla@example.com",
    address: "Sector 17, Chandigarh, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
