export const idCardDetails = {
    slNo: "023",
    idCardPhoto: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?fit=crop&w=800&q=80",
    name: "Riya Sen",
    firstName: "Riya",
    middleName: "-",
    lastName: "Sen",
    fatherSName: "Prosenjit Sen",
    fatherFirstName: "Prosenjit",
    fatherMiddleName: "-",
    fatherLastName: "Sen",
    dateOfBirth: "19-May-2003",
    gender: "Female",
    designation: "Certified Cyber Defense Student",
    department: "National Cyber Crime Training Institute",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official Academic Student ID",
    employeeStudentMemberId: "CRCCF-STU-023",
    idCardNumber: "IDC-2024-STU23",
    issueDate: "01-Aug-2023",
    validFrom: "01-Aug-2023",
    expiryDate: "31-Jul-2025",
    mobileNumber: "+91 9831223344",
    emailId: "riya.sen@students.crccf.org",
    address: "College Square, Kolkata, West Bengal, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Enrolled in Post-Graduate Diploma in Incident Response"
};
