export const letterDetails = {
    slNo: "Sample Sl No",
    letterPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    letterNumber: "Sample Letter Number",
    letterType: "Sample Letter Type",
    letterSubject: "Sample Letter Subject",
    letterDate: "Sample Letter Date",
    senderName: "Sample Sender Name",
    senderDesignation: "Sample Sender Designation",
    senderDepartment: "Sample Sender Department",
    senderOrganization: "Sample Sender Organization",
    recipientName: "Sample Recipient Name",
    recipientDesignation: "Sample Recipient Designation",
    recipientDepartment: "Sample Recipient Department",
    recipientOrganization: "Sample Recipient Organization",
    letterPurpose: "Sample Letter Purpose",
    referenceNumber: "Sample Reference Number",
    issuingAuthority: "Sample Issuing Authority",
    authorizedSignatoryName: "Sample Authorized Signatory Name",
    contactNumber: "Sample Contact Number",
    emailId: "Sample Email ID",
    letterStatus: "Sample Letter Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
    remarks: "Sample Remarks",
};