export const certificateDetails = {
    slNo: "022",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Prof. Harish Sundaram",
    certificateHolderFirstName: "Harish",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Sundaram",
    fatherSName: "N. Sundaram",
    fatherFirstName: "N.",
    fatherMiddleName: "-",
    fatherLastName: "Sundaram",
    dateOfBirth: "22-May-1975",
    gender: "Male",
    certificateName: "Mentorship Certificate",
    certificateType: "Academic Mentorship Recognition",
    courseQualificationName: "Master Mentor in Digital Forensics & Cyber Defense Cohorts",
    institutionName: "CRCCF Academic Mentorship Council",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-MNT-2024-022",
    certificateNumber: "CERT-MNT-8922",
    issueDate: "15-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Distinguished Mentor",
    certificateValidity: "Permanent Honor",
    issuingAuthority: "Dean of Mentorship Programs, CRCCF",
    mobileNumber: "+91 9876543122",
    emailId: "prof.harish@example.com",
    address: "Anna Nagar, Chennai, Tamil Nadu, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
