export const certificateDetails = {
    slNo: "035",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Rohit Varma",
    certificateHolderFirstName: "Rohit",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Varma",
    fatherSName: "Rajendra Varma",
    fatherFirstName: "Rajendra",
    fatherMiddleName: "-",
    fatherLastName: "Varma",
    dateOfBirth: "03-Oct-1995",
    gender: "Male",
    certificateName: "Network Security Certificate",
    certificateType: "Infrastructure Security Credential",
    courseQualificationName: "Next-Gen Firewall, Zero-Trust Architecture & Packet Forensics",
    institutionName: "National Network Defense Institute",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-NSC-2024-035",
    certificateNumber: "CERT-NSC-8935",
    issueDate: "11-Sep-2024",
    passingYear: "2024",
    gradeMarks: "Distinction (92%)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Chief Network Architect, CRCCF",
    mobileNumber: "+91 9876543135",
    emailId: "rohit.varma@example.com",
    address: "Panampilly Nagar, Kochi, Kerala, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
