export const idCardDetails = {
    slNo: "012",
    idCardPhoto: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?fit=crop&w=800&q=80",
    name: "Sameer Joshi",
    firstName: "Sameer",
    middleName: "-",
    lastName: "Joshi",
    fatherSName: "Mahesh Joshi",
    fatherFirstName: "Mahesh",
    fatherMiddleName: "-",
    fatherLastName: "Joshi",
    dateOfBirth: "16-Sep-1989",
    gender: "Male",
    designation: "Principal Reverse Engineer",
    department: "Advanced Threat & Malware Lab",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Technical Expert ID",
    employeeStudentMemberId: "CRCCF-EXP-012",
    idCardNumber: "IDC-2024-EXP12",
    issueDate: "01-Apr-2023",
    validFrom: "01-Apr-2023",
    expiryDate: "31-Mar-2027",
    mobileNumber: "+91 9920114477",
    emailId: "sameer.joshi@crccf.org",
    address: "Hinjawadi Phase 2, IT Park, Pune, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Clearance for level-4 air-gapped malware analysis chamber"
};
