export const certificateDetails = {
    slNo: "032",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Manish Tiwari",
    certificateHolderFirstName: "Manish",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Tiwari",
    fatherSName: "Shrikant Tiwari",
    fatherFirstName: "Shrikant",
    fatherMiddleName: "-",
    fatherLastName: "Tiwari",
    dateOfBirth: "09-Sep-1994",
    gender: "Male",
    certificateName: "Cyber Incident Response Certificate",
    certificateType: "Incident Response Practitioner",
    courseQualificationName: "CSIRT Leadership, Containment & Forensic Remediation",
    institutionName: "CRCCF Incident Management Academy",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-IRC-2024-032",
    certificateNumber: "CERT-IRC-8932",
    issueDate: "28-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Commander, CSIRT Operations, CRCCF",
    mobileNumber: "+91 9876543132",
    emailId: "manish.tiwari@example.com",
    address: "Arera Colony, Bhopal, Madhya Pradesh, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
