export const licenceDetails = {
    licenseHolderName: "Subrajit",
    fatherName: "Sanjay Kumar",
    dob: "15-Aug-1995",
    gender: "Male",
    designation: "Managing Director",
    department: "Executive Board",
    directorIdentificationNumber: "DIN-8829103",
    licenseRegistrationNumber: "LIC-009",
    purposeOfLicence: "Commercial Trading",
    useOfLicence: "Import & Export Goods",
    roleOfLicence: "Primary Licensee",
    issuingAuthority: "State Trade Commission",
    licenseValidity: "10 Years",
    expiryDate: "31-Dec-2033",
    mobile: "+91 9876543210",
    mail: "subrajit@example.com",
    address: "123, Tech Park Avenue, Block C, Bhubaneswar, India",
    status: "Active",

    orgName: "Global Trade Solutions Pvt Ltd",
    orgType: "Private Limited Company",
    orgActivity: "Logistics and Trading",
    orgStatus: "Active",
    orgAddress: "456, Commerce Plaza, New Delhi, India",
    orgCinNumber: "U74999DL2023PTC123456",
    orgService: "B2B Supply Chain",
    orgMailId: "contact@globaltradesolutions.in",
    orgMobile: "+91 8877665544",
    orgWebsite: "www.globaltradesolutions.in"
};
