export const certificateDetails = {
    slNo: "015",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Megha Kapoor",
    certificateHolderFirstName: "Megha",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Kapoor",
    fatherSName: "Sunil Kapoor",
    fatherFirstName: "Sunil",
    fatherMiddleName: "-",
    fatherLastName: "Kapoor",
    dateOfBirth: "21-Feb-1998",
    gender: "Female",
    certificateName: "Appreciation Certificate",
    certificateType: "Official Commendation",
    courseQualificationName: "Exceptional Contribution to Cybercrime Awareness & Public Outreach",
    institutionName: "CRCCF Directorate of Public Engagement",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-AC-2024-015",
    certificateNumber: "CERT-AC-8915",
    issueDate: "15-Aug-2024",
    passingYear: "2024",
    gradeMarks: "Merit of High Honor",
    certificateValidity: "Lifetime",
    issuingAuthority: "President, CRCCF",
    mobileNumber: "+91 9876543115",
    emailId: "megha.kapoor@example.com",
    address: "Vasant Kunj, New Delhi, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
