export const noticeDetails = {
    slNo: "Sample Sl No",
    noticePreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    noticeNumber: "Sample Notice Number",
    noticeTitle: "Sample Notice Title",
    noticeType: "Sample Notice Type",
    noticeSubject: "Sample Notice Subject",
    noticeDate: "Sample Notice Date",
    effectiveDate: "Sample Effective Date",
    expiryDate: "Sample Expiry Date",
    issuingOrganization: "Sample Issuing Organization",
    issuingDepartment: "Sample Issuing Department",
    issuingAuthority: "Sample Issuing Authority",
    noticePurpose: "Sample Notice Purpose",
    applicableTo: "Sample Applicable To",
    referenceNumber: "Sample Reference Number",
    authorizedSignatory: "Sample Authorized Signatory",
    contactNumber: "Sample Contact Number",
    emailId: "Sample Email ID",
    address: "Sample Address",
    noticeStatus: "Sample Notice Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
    remarks: "Sample Remarks",
};