export const noticeDetails = {
    slNo: "001",
    noticePreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    noticeNumber: "NOT-2023-4412",
    noticeRegistrationId: "NTC-009",
    referenceNumber: "NTC-009",
    noticeTitle: "Official Compliance & Statutory Advisory",
    noticeType: "Public Regulatory Advisory",
    noticeSubject: "Implementation of Cyber Security Auditing Mandate",
    noticeDate: "10-Nov-2023",
    effectiveDate: "15-Nov-2023",
    expiryDate: "31-Dec-2025",
    issuingOrganization: "CR Cyber Crime Foundation",
    issuingDepartment: "Legal & Regulatory Compliance Directorate",
    issuingAuthority: "State Cyber Safety Commission",
    noticePurpose: "Statutory Enforcement of Digital Forensic Standards",
    applicableTo: "All Registered Institutional & Corporate Affiliates",
    authorizedSignatory: "Subrajit Sharma",
    authorizedSignatoryFirstName: "Subrajit",
    authorizedSignatoryMiddleName: "-",
    authorizedSignatoryLastName: "Sharma",
    contactNumber: "+91 9876543210",
    emailId: "legal@crccf.org",
    address: "Plot 108, Cyber City Phase 2, Patia, Bhubaneswar, Odisha 751024",
    noticeStatus: "Published & Active",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Legal Records Cell",
    remarks: "Official regulatory notice verified through administrative registry",
};