export const certificateDetails = {
    slNo: "038",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Sanjay Hegde",
    certificateHolderFirstName: "Sanjay",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Hegde",
    fatherSName: "Narayana Hegde",
    fatherFirstName: "Narayana",
    fatherMiddleName: "-",
    fatherLastName: "Hegde",
    dateOfBirth: "16-Apr-1986",
    gender: "Male",
    certificateName: "Professional Development Certificate",
    certificateType: "Continuing Executive Development",
    courseQualificationName: "CISO Leadership, Regulatory Compliance & Threat Defense Governance",
    institutionName: "CRCCF Executive Education Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-PDC-2024-038",
    certificateNumber: "CERT-PDC-8938",
    issueDate: "05-Sep-2024",
    passingYear: "2024",
    gradeMarks: "Executive Honor",
    certificateValidity: "Lifetime",
    issuingAuthority: "Executive Dean, CRCCF",
    mobileNumber: "+91 9876543138",
    emailId: "sanjay.hegde@example.com",
    address: "Malleshwaram, Bengaluru, Karnataka, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
