export const certificateDetails = {
    slNo: "031",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Simran Kaur",
    certificateHolderFirstName: "Simran",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Kaur",
    fatherSName: "Gurpreet Singh",
    fatherFirstName: "Gurpreet",
    fatherMiddleName: "-",
    fatherLastName: "Singh",
    dateOfBirth: "17-Jul-2003",
    gender: "Female",
    certificateName: "Cyber Safety Ambassador Certificate",
    certificateType: "National Ambassador Credential",
    courseQualificationName: "Campus Cyber Safety Advocacy & Anti-Cyberbullying Program",
    institutionName: "CRCCF Youth Ambassador Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-CSA-2024-031",
    certificateNumber: "CERT-CSA-8931",
    issueDate: "10-Nov-2024",
    passingYear: "2024",
    gradeMarks: "Ambassador of Merit",
    certificateValidity: "Lifetime",
    issuingAuthority: "National Ambassador Coordinator, CRCCF",
    mobileNumber: "+91 9876543131",
    emailId: "simran.kaur@example.com",
    address: "Ranjit Avenue, Amritsar, Punjab, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
