export const certificateDetails = {
    slNo: "007",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Manisha Patel",
    certificateHolderFirstName: "Manisha",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Patel",
    fatherSName: "Girish Patel",
    fatherFirstName: "Girish",
    fatherMiddleName: "-",
    fatherLastName: "Patel",
    dateOfBirth: "29-Aug-1997",
    gender: "Female",
    certificateName: "Technical Education Certificate",
    certificateType: "Advanced Technical Engineering",
    courseQualificationName: "Cloud Security Architecture & DevSecOps Engineering",
    institutionName: "Center for Technical Cyber Defense",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-TEC-2024-007",
    certificateNumber: "CERT-TEC-8907",
    issueDate: "18-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Distinction (94%)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Chief Technology Advisor, CRCCF",
    mobileNumber: "+91 9876543107",
    emailId: "manisha.patel@example.com",
    address: "SG Highway, Ahmedabad, Gujarat, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
