export const partnershipDetails = {
    slNo: "Sample Sl No",
    partnershipDocumentPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    partnershipRegistrationNumber: "Sample Partnership Registration Number",
    firstOrganizationName: "Sample First Organization Name",
    firstOrganizationType: "Sample First Organization Type",
    firstOrganizationRepresentative: "Sample First Organization Representative",
    firstRepresentativeDesignation: "Sample First Representative Designation",
    secondOrganizationName: "Sample Second Organization Name",
    secondOrganizationType: "Sample Second Organization Type",
    secondOrganizationRepresentative: "Sample Second Organization Representative",
    secondRepresentativeDesignation: "Sample Second Representative Designation",
    partnershipTitle: "Sample Partnership Title",
    partnershipType: "Sample Partnership Type",
    partnershipPurpose: "Sample Partnership Purpose",
    partnershipActivity: "Sample Partnership Activity",
    partnershipStartDate: "Sample Partnership Start Date",
    partnershipEndDate: "Sample Partnership End Date",
    partnershipStatus: "Sample Partnership Status",
    authorizedSignatory: "Sample Authorized Signatory",
    signatoryDesignation: "Sample Signatory Designation",
    mobileNumber: "Sample Mobile Number",
    emailId: "Sample Email ID",
    website: "Sample Website",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
};