export const idCardDetails = {
    slNo: "040",
    idCardPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?fit=crop&w=800&q=80",
    name: "Hon. Justice K. Ramanathan",
    firstName: "K.",
    middleName: "-",
    lastName: "Ramanathan",
    fatherSName: "Late Justice Ramanathan",
    fatherFirstName: "Late",
    fatherMiddleName: "Justice",
    fatherLastName: "Ramanathan",
    dateOfBirth: "01-Jan-1958",
    gender: "Male",
    designation: "Invited Keynote Dignitary",
    department: "Executive VIP Protocol Directorate",
    organizationName: "CR Cyber Crime Foundation",
    idCardType: "Official VIP Guest ID",
    employeeStudentMemberId: "CRCCF-GST-040",
    idCardNumber: "IDC-2024-GST40",
    issueDate: "15-Sep-2026",
    validFrom: "15-Sep-2026",
    expiryDate: "16-Sep-2026",
    mobileNumber: "+91 9811009988",
    emailId: "guest.protocol@crccf.org",
    address: "Chief Justice Bungalow, New Delhi, India",
    issuedBy: "Office of the Registrar, CRCCF",
    approvedBy: "Rakesh Sharma",
    approvedByFirstName: "Rakesh",
    approvedByMiddleName: "-",
    approvedByLastName: "Sharma",
    idCardStatus: "Active & Valid",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Security Administration",
    remarks: "Chief Guest for National Cybersecurity Annual Valedictory"
};
