export const certificateDetails = {
    slNo: "039",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Anupam Goswami",
    certificateHolderFirstName: "Anupam",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Goswami",
    fatherSName: "B. N. Goswami",
    fatherFirstName: "B.",
    fatherMiddleName: "N.",
    fatherLastName: "Goswami",
    dateOfBirth: "11-May-1994",
    gender: "Male",
    certificateName: "Information Security Certificate",
    certificateType: "ISMS Security Certification",
    courseQualificationName: "ISO/IEC 27001 ISMS Lead Auditor & Security Controls Implementation",
    institutionName: "CRCCF Compliance & Information Security Directorate",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-ISC-2024-039",
    certificateNumber: "CERT-ISC-8939",
    issueDate: "12-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Chief Security Officer, CRCCF",
    mobileNumber: "+91 9876543139",
    emailId: "anupam.goswami@example.com",
    address: "GS Road, Guwahati, Assam, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
