export const licenseDetails = {
    slNo: "Sample Sl No",
    licenseHolderPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    licenseHolderName: "Sample License Holder Name",
    fatherSName: "Sample Father's Name",
    dateOfBirth: "Sample Date of Birth",
    gender: "Sample Gender",
    designation: "Sample Designation",
    department: "Sample Department",
    directorIdentificationNumberDin: "Sample Director Identification Number (DIN)",
    licenseRegistrationNumber: "Sample License Registration Number",
    licenseType: "Sample License Type",
    purposeOfLicense: "Sample Purpose of License",
    useOfLicense: "Sample Use of License",
    roleOfLicense: "Sample Role of License",
    issuingAuthority: "Sample Issuing Authority",
    issueDate: "Sample Issue Date",
    licenseValidity: "Sample License Validity",
    expiryDate: "Sample Expiry Date",
    organizationName: "Sample Organization Name",
    organizationType: "Sample Organization Type",
    organizationActivity: "Sample Organization Activity",
    organizationStatus: "Sample Organization Status",
    organizationAddress: "Sample Organization Address",
    organizationCinNumber: "Sample Organization CIN Number",
    organizationServices: "Sample Organization Services",
    organizationEmailId: "Sample Organization Email ID",
    organizationMobileNumber: "Sample Organization Mobile Number",
    organizationWebsite: "Sample Organization Website",
    licenseHolderMobileNumber: "Sample License Holder Mobile Number",
    licenseHolderEmailId: "Sample License Holder Email ID",
    licenseHolderAddress: "Sample License Holder Address",
    licenseStatus: "Sample License Status",
    verificationDate: "Sample Verification Date",
    verifiedBy: "Sample Verified By",
    remarks: "Sample Remarks",
};