export const licenseDetails = {
    slNo: "001",
    licenseHolderPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    licenseHolderName: "Subrajit Sharma",
    licenseHolderFirstName: "Subrajit",
    licenseHolderMiddleName: "-",
    licenseHolderLastName: "Sharma",
    fatherSName: "Sanjay Kumar",
    fatherFirstName: "Sanjay",
    fatherMiddleName: "-",
    fatherLastName: "Kumar",
    dateOfBirth: "15-Aug-1995",
    gender: "Male",
    designation: "Managing Director",
    department: "Executive Management",
    directorIdentificationNumberDin: "DIN-08912456",
    licenseRegistrationNumber: "LIC-2023-8891",
    licenseType: "Commercial Operations License",
    purposeOfLicense: "Cybersecurity & IT Infrastructure Auditing",
    useOfLicense: "Enterprise Verification & Security Consulting",
    roleOfLicense: "Primary Corporate Compliance",
    issuingAuthority: "Ministry of Corporate Affairs & CRCCF Regulatory Council",
    issueDate: "12-Jan-2023",
    licenseValidity: "5 Years",
    expiryDate: "11-Jan-2028",
    organizationName: "CR Cyber Crime Foundation",
    organizationType: "Section 8 Non-Profit Technology Entity",
    organizationActivity: "Cyber Defence & Digital Safety Research",
    organizationStatus: "Active / Recognized",
    organizationAddress: "Plot 108, Cyber City Phase 2, Patia, Bhubaneswar, Odisha 751024",
    organizationCinNumber: "U72900OR2021NPL038910",
    organizationServices: "Cyber Crime Forensics, Fraud Verification, Threat Intelligence",
    organizationEmailId: "compliance@crccf.org",
    organizationMobileNumber: "+91 9876543210",
    organizationWebsite: "https://crccf.org",
    licenseHolderMobileNumber: "+91 9876543210",
    licenseHolderEmailId: "subrajit@example.com",
    licenseHolderAddress: "123, Tech Park Avenue, Block C, Bhubaneswar, India",
    licenseStatus: "Verified & Active",
    verificationDate: "12-Sep-2026",
    verifiedBy: "CRCCF Document Verification Cell",
    remarks: "All credentials verified and compliant with national regulatory standards",
};