export const certificateDetails = {
    slNo: "018",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Amitav Ghosh",
    certificateHolderFirstName: "Amitav",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Ghosh",
    fatherSName: "Debabrata Ghosh",
    fatherFirstName: "Debabrata",
    fatherMiddleName: "-",
    fatherLastName: "Ghosh",
    dateOfBirth: "03-Dec-1992",
    gender: "Male",
    certificateName: "Excellence Award Certificate",
    certificateType: "Annual Excellence Honor",
    courseQualificationName: "CRCCF Annual Excellence Award for Automated Forensic Tools",
    institutionName: "CRCCF Honors & Awards Committee",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-EAC-2024-018",
    certificateNumber: "CERT-EAC-8918",
    issueDate: "26-Jan-2024",
    passingYear: "2024",
    gradeMarks: "Award Winner (First Place)",
    certificateValidity: "Permanent Honor",
    issuingAuthority: "Chairman, CRCCF Governing Council",
    mobileNumber: "+91 9876543118",
    emailId: "amitav.ghosh@example.com",
    address: "Salt Lake Sector 1, Kolkata, West Bengal, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
