export const certificateDetails = {
    slNo: "026",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Deepak Malhotra",
    certificateHolderFirstName: "Deepak",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Malhotra",
    fatherSName: "R. K. Malhotra",
    fatherFirstName: "R.",
    fatherMiddleName: "K.",
    fatherLastName: "Malhotra",
    dateOfBirth: "15-Dec-1995",
    gender: "Male",
    certificateName: "Cyber Security Training Certificate",
    certificateType: "Certified Practitioner Training",
    courseQualificationName: "Enterprise SOC Analyst Level-2 Intensive Program",
    institutionName: "Cyber Defense Academy",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-CST-2024-026",
    certificateNumber: "CERT-CST-8926",
    issueDate: "22-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Grade A+ (Distinction)",
    certificateValidity: "Lifetime",
    issuingAuthority: "Head of Training Programs, CRCCF",
    mobileNumber: "+91 9876543126",
    emailId: "deepak.malhotra@example.com",
    address: "Rohini Sector 9, New Delhi, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
