export const certificateDetails = {
    slNo: "016",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Nikhil Joshi",
    certificateHolderFirstName: "Nikhil",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Joshi",
    fatherSName: "Kailash Joshi",
    fatherFirstName: "Kailash",
    fatherMiddleName: "-",
    fatherLastName: "Joshi",
    dateOfBirth: "11-Oct-1995",
    gender: "Male",
    certificateName: "Achievement Certificate",
    certificateType: "Specialized Achievement Credential",
    courseQualificationName: "Outstanding Vulnerability Research & Zero-Day Discovery",
    institutionName: "Center for Vulnerability Research & Defense",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-ACH-2024-016",
    certificateNumber: "CERT-ACH-8916",
    issueDate: "09-Sep-2024",
    passingYear: "2024",
    gradeMarks: "Gold Tier Achievement",
    certificateValidity: "Lifetime",
    issuingAuthority: "Chief of Cyber Research, CRCCF",
    mobileNumber: "+91 9876543116",
    emailId: "nikhil.joshi@example.com",
    address: "Kothrud, Pune, Maharashtra, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
