export const certificateDetails = {
    slNo: "036",
    certificatePhotoPreview: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=800&q=80",
    certificateHolderName: "Sunita Devi",
    certificateHolderFirstName: "Sunita",
    certificateHolderMiddleName: "-",
    certificateHolderLastName: "Devi",
    fatherSName: "Ramchandra Prasad",
    fatherFirstName: "Ramchandra",
    fatherMiddleName: "-",
    fatherLastName: "Prasad",
    dateOfBirth: "12-Nov-1988",
    gender: "Female",
    certificateName: "Digital Literacy Certificate",
    certificateType: "Community Digital Competency",
    courseQualificationName: "Community Digital Safety, Net Banking Protection & Safe Browsing",
    institutionName: "CRCCF Community Digital Empowerment Wing",
    boardUniversity: "Cyber Crime Research & Crime Foundation (CRCCF)",
    registrationNumber: "CRCCF-DLC-2024-036",
    certificateNumber: "CERT-DLC-8936",
    issueDate: "01-Oct-2024",
    passingYear: "2024",
    gradeMarks: "Grade A",
    certificateValidity: "Lifetime",
    issuingAuthority: "Coordinator, Digital India Wing, CRCCF",
    mobileNumber: "+91 9876543136",
    emailId: "sunita.devi@example.com",
    address: "Kankarbagh, Patna, Bihar, India",
    certificateStatus: "Authentic & Verified",
    verificationDate: "15-Sep-2026",
    verifiedBy: "CRCCF Certification Audit Directorate"
};
